# Code actions carry each fix of a diagnostic the range touches: a likely
# respelling, offered and not preferred, and an exact removal of `mut`,
# preferred.  A range that touches no diagnostic gets none.  The fixes
# are the ones refine's report carries, as workspace edits.
-> {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{}}}
-> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///workspace/misspelt.ldn","languageId":"landin","version":1,"text":"count: (value: u32) -> (result: u32) = value + 1 end count\n\ntotal: (limit: u32) -> (result: u32) =\n    mut sum: u32 = 0\n    while sum < limt do\n        sum = cuont(value: sum)\n    end while\n    result = sum\nend total\n"}}}
-> {"jsonrpc":"2.0","id":2,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///workspace/misspelt.ldn"},"range":{"start":{"line":4,"character":17},"end":{"line":4,"character":17}},"context":{"diagnostics":[]}}}
-> {"jsonrpc":"2.0","id":3,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///workspace/misspelt.ldn"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":5}},"context":{"diagnostics":[]}}}
-> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///workspace/unmut.ldn","languageId":"landin","version":1,"text":"count_to: (target: u32) -> (reached: u32) =\n    mut total: u32 = 0\n    mut step: u32 = 1\n    total += step + target\n    reached = total\nend count_to\n"}}}
-> {"jsonrpc":"2.0","id":4,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///workspace/unmut.ldn"},"range":{"start":{"line":2,"character":0},"end":{"line":2,"character":30}},"context":{"diagnostics":[]}}}
-> {"jsonrpc":"2.0","id":5,"method":"shutdown"}
-> {"jsonrpc":"2.0","method":"exit"}
<- {"jsonrpc":"2.0","id":1,"result":{"capabilities":{"positionEncoding":"utf-16","textDocumentSync":{"openClose":true,"change":1},"definitionProvider":true,"hoverProvider":true,"documentFormattingProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix"]}},"serverInfo":{"name":"refine"}}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/misspelt.ldn","version":1,"diagnostics":[{"range":{"start":{"line":4,"character":16},"end":{"line":4,"character":20}},"severity":1,"code":"L0201","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0201"},"source":"refine","message":"`limt` is not declared in any scope this reaches\nnote: [1860]: a name that is not in scope is a misspelling, not a new binding"},{"range":{"start":{"line":5,"character":14},"end":{"line":5,"character":19}},"severity":1,"code":"L0201","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0201"},"source":"refine","message":"`cuont` is not declared in any scope this reaches\nnote: [1860]: a name that is not in scope is a misspelling, not a new binding"}]}}
<- {"jsonrpc":"2.0","id":2,"result":[{"title":"did you mean `limit`?","kind":"quickfix","diagnostics":[{"range":{"start":{"line":4,"character":16},"end":{"line":4,"character":20}},"severity":1,"code":"L0201","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0201"},"source":"refine","message":"`limt` is not declared in any scope this reaches\nnote: [1860]: a name that is not in scope is a misspelling, not a new binding"}],"isPreferred":false,"edit":{"changes":{"file:///workspace/misspelt.ldn":[{"range":{"start":{"line":4,"character":16},"end":{"line":4,"character":20}},"newText":"limit"}]}}}]}
<- {"jsonrpc":"2.0","id":3,"result":[]}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/unmut.ldn","version":1,"diagnostics":[{"range":{"start":{"line":2,"character":4},"end":{"line":2,"character":7}},"severity":2,"code":"L0326","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0326"},"source":"refine","message":"`step` is declared `mut` and nothing writes it\nnote: D251: a warning, and the program is accepted; without `mut` it means the same"}]}}
<- {"jsonrpc":"2.0","id":4,"result":[{"title":"declare `step` without `mut`","kind":"quickfix","diagnostics":[{"range":{"start":{"line":2,"character":4},"end":{"line":2,"character":7}},"severity":2,"code":"L0326","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0326"},"source":"refine","message":"`step` is declared `mut` and nothing writes it\nnote: D251: a warning, and the program is accepted; without `mut` it means the same"}],"isPreferred":true,"edit":{"changes":{"file:///workspace/unmut.ldn":[{"range":{"start":{"line":2,"character":4},"end":{"line":2,"character":8}},"newText":""}]}}}]}
<- {"jsonrpc":"2.0","id":5,"result":null}
exit: 0
