(require 'treesit)
(add-to-list 'treesit-extra-load-path (getenv "LANDIN_TREE_SITTER_LIB"))
(unless (treesit-ready-p 'landin)
  (error "Landin tree-sitter grammar is unavailable"))

(add-to-list 'load-path (concat (getenv "LANDIN_HIGHLIGHT_ROOT") "/emacs"))
(require 'landin-mode)
(find-file (concat (getenv "LANDIN_HIGHLIGHT_ROOT") "/tests/structural.ldn"))
(unless (eq major-mode 'landin-ts-mode)
  (error "expected landin-ts-mode, got %s" major-mode))
(font-lock-ensure)

(defun landin-test-treesit-face (text expected)
  (goto-char (point-min))
  (unless (search-forward text nil t)
    (error "missing tree-sitter smoke-test text: %s" text))
  (let ((face (get-text-property (match-beginning 0) 'face)))
    (unless (or (eq face expected) (and (listp face) (memq expected face)))
      (error "%s: expected %s, got %s" text expected face))))

(landin-test-treesit-face "outer block comment" 'font-lock-comment-face)
(landin-test-treesit-face "public" 'font-lock-keyword-face)
(landin-test-treesit-face "lenof" 'font-lock-keyword-face)
(landin-test-treesit-face "host_write" 'font-lock-string-face)
(landin-test-treesit-face "landin_increment" 'font-lock-function-name-face)
(landin-test-treesit-face "add(" 'font-lock-function-call-face)
(landin-test-treesit-face "+" 'font-lock-operator-face)
(landin-test-treesit-face "i32" 'font-lock-builtin-face)
(with-temp-buffer
  (insert "sample: () -> () =\n    raw: utf8 = \"\"\"raw text\"\"\"\nend sample\n")
  (landin-ts-mode)
  (font-lock-ensure)
  (landin-test-treesit-face "raw text" 'font-lock-string-face))
(kill-emacs 0)
