(add-to-list 'load-path (concat (getenv "LANDIN_HIGHLIGHT_ROOT") "/emacs"))
(require 'landin-mode)
(find-file (concat (getenv "LANDIN_HIGHLIGHT_ROOT") "/tests/lexical.ldn"))
(landin-mode)
(font-lock-ensure)

(defun landin-test-face-at (text expected)
  (goto-char (point-min))
  (unless (search-forward text nil t)
    (error "missing smoke-test text: %s" text))
  (let ((face (get-text-property (1- (point)) 'face)))
    (unless (or (eq face expected) (and (listp face) (memq expected face)))
      (error "%s: expected %s, got %s" text expected face))))

(unless (eq major-mode 'landin-mode)
  (error "expected landin-mode, got %s" major-mode))
(unless (string= comment-start "-- ")
  (error "Landin mode did not install comment syntax"))
(landin-test-face-at "public" 'font-lock-keyword-face)
(landin-test-face-at "u23" 'font-lock-type-face)
(dolist (module '("compiler" "assembler" "linker"))
  (landin-test-face-at module 'font-lock-builtin-face))
(landin-test-face-at "documentation comment" 'font-lock-doc-face)
(landin-test-face-at "nested block comment" 'font-lock-comment-face)
(landin-test-face-at "escaped" 'font-lock-string-face)

(dolist (width '(3 4 5))
  (with-temp-buffer
    (let ((delimiter (make-string width ?\")))
      (insert delimiter "if true -- marker\n" delimiter)
      (landin-mode)
      (goto-char (point-min))
      (unless (and (landin--match-raw-string (point-max))
                   (= (match-beginning 0) (point-min))
                   (= (match-end 0) (point-max)))
        (error "raw literal delimiter of %d quotes was not matched" width))
      (font-lock-ensure)
      (landin-test-face-at "if true" 'font-lock-string-face)
      (landin-test-face-at "marker" 'font-lock-string-face))))

(dolist (comment '("-- \"\"\"\"\n"
                   "--( block\n\"\"\"\"\n)--\n"))
  (with-temp-buffer
    (insert comment "public main: () -> none =\n")
    (landin-mode)
    (goto-char (point-min))
    (when (landin--match-raw-string (point-max))
      (error "comment quote run was matched as a raw literal"))
    (font-lock-ensure)
    (landin-test-face-at "public" 'font-lock-keyword-face)))

(kill-emacs 0)
