/* Generated by bindings/generate.py; do not edit. */
#include "exports.h"
#include <stdarg.h>
#include <stdlib.h>

_Static_assert(__builtin_types_compatible_p(BindingMode, long), "BindingMode compatible type disagrees with its generated integer alias");
_Static_assert(sizeof(BindingMode) == 8, "BindingMode size disagrees with its generated integer alias");
_Static_assert(_Alignof(BindingMode) == 8, "BindingMode alignment disagrees with its generated integer alias");
_Static_assert(__builtin_types_compatible_p(BindingSmall, unsigned int), "BindingSmall compatible type disagrees with its generated integer alias");
_Static_assert(sizeof(BindingSmall) == 4, "BindingSmall size disagrees with its generated integer alias");
_Static_assert(_Alignof(BindingSmall) == 4, "BindingSmall alignment disagrees with its generated integer alias");
_Static_assert(sizeof(BindingMatrix) == 24, "BindingMatrix size disagrees with Landin layout(c)");
_Static_assert(_Alignof(BindingMatrix) == 4, "BindingMatrix alignment disagrees with Landin layout(c)");
_Static_assert(__builtin_offsetof(BindingMatrix, values) == 0, "BindingMatrix.values offset disagrees with Landin layout(c)");
_Static_assert(sizeof(BindingNativeView) == 8, "BindingNativeView size disagrees with Landin layout(c)");
_Static_assert(_Alignof(BindingNativeView) == 8, "BindingNativeView alignment disagrees with Landin layout(c)");
_Static_assert(__builtin_offsetof(BindingNativeView, data) == 0, "BindingNativeView.data offset disagrees with Landin layout(c)");
_Static_assert(sizeof(BindingPair) == 16, "BindingPair size disagrees with Landin layout(c)");
_Static_assert(_Alignof(BindingPair) == 8, "BindingPair alignment disagrees with Landin layout(c)");
_Static_assert(__builtin_offsetof(BindingPair, real) == 0, "BindingPair.real offset disagrees with Landin layout(c)");
_Static_assert(__builtin_offsetof(BindingPair, count) == 8, "BindingPair.count offset disagrees with Landin layout(c)");

struct landin_r440_bindings_binding_borrow_callback_cell_type { binding_borrow_callback value; };
struct landin_r440_bindings_binding_callback_cell_type { binding_callback value; };
_Thread_local int binding_tls_counter;

void * landin_r440_bindings_binding_borrow_callback_cell_allocate(void)
{
    return calloc(1, sizeof(struct landin_r440_bindings_binding_borrow_callback_cell_type));
}

void landin_r440_bindings_binding_borrow_callback_cell_release(void *cell_)
{
    free(cell_);
}

void landin_r440_bindings_binding_borrow_callback_cell_clear(void *cell_)
{
    ((struct landin_r440_bindings_binding_borrow_callback_cell_type *)cell_)->value = 0;
}

void landin_r440_bindings_binding_borrow_callback_cell_set(void *cell_, binding_borrow_callback value_)
{
    ((struct landin_r440_bindings_binding_borrow_callback_cell_type *)cell_)->value = value_;
}

_Bool landin_r440_bindings_binding_borrow_callback_cell_present(const void *cell_)
{
    return ((const struct landin_r440_bindings_binding_borrow_callback_cell_type *)cell_)->value != 0;
}

binding_borrow_callback landin_r440_bindings_binding_borrow_callback_cell_access(const void *cell_)
{
    binding_borrow_callback value_ = ((const struct landin_r440_bindings_binding_borrow_callback_cell_type *)cell_)->value;
    if (value_ == 0) __builtin_trap();
    return value_;
}

_Bool landin_r440_bindings_binding_borrow_callback_cell_invoke(const void *cell_, const int *argument_1, const int **result)
{
    if (((const struct landin_r440_bindings_binding_borrow_callback_cell_type *)cell_)->value == 0) return 0;
    *result = ((const struct landin_r440_bindings_binding_borrow_callback_cell_type *)cell_)->value(argument_1);
    return 1;
}

void * landin_r440_bindings_binding_callback_cell_allocate(void)
{
    return calloc(1, sizeof(struct landin_r440_bindings_binding_callback_cell_type));
}

void landin_r440_bindings_binding_callback_cell_release(void *cell_)
{
    free(cell_);
}

void landin_r440_bindings_binding_callback_cell_clear(void *cell_)
{
    ((struct landin_r440_bindings_binding_callback_cell_type *)cell_)->value = 0;
}

void landin_r440_bindings_binding_callback_cell_set(void *cell_, binding_callback value_)
{
    ((struct landin_r440_bindings_binding_callback_cell_type *)cell_)->value = value_;
}

_Bool landin_r440_bindings_binding_callback_cell_present(const void *cell_)
{
    return ((const struct landin_r440_bindings_binding_callback_cell_type *)cell_)->value != 0;
}

binding_callback landin_r440_bindings_binding_callback_cell_access(const void *cell_)
{
    binding_callback value_ = ((const struct landin_r440_bindings_binding_callback_cell_type *)cell_)->value;
    if (value_ == 0) __builtin_trap();
    return value_;
}

_Bool landin_r440_bindings_binding_callback_cell_invoke(const void *cell_, int argument_1, int *result)
{
    if (((const struct landin_r440_bindings_binding_callback_cell_type *)cell_)->value == 0) return 0;
    *result = ((const struct landin_r440_bindings_binding_callback_cell_type *)cell_)->value(argument_1);
    return 1;
}

void * landin_r440_bindings_binding_bits_allocate(void)
{
    return calloc(1, sizeof(BindingBits));
}

void landin_r440_bindings_binding_bits_release(void *object)
{
    free(object);
}

void landin_r440_bindings_binding_bits_copy(void *target, const void *source)
{
    *(BindingBits *)target = *(const BindingBits *)source;
}

__SIZE_TYPE__ landin_r440_bindings_binding_bits_size(void)
{
    return sizeof(BindingBits);
}

__SIZE_TYPE__ landin_r440_bindings_binding_bits_alignment(void)
{
    return _Alignof(BindingBits);
}

int landin_r440_bindings_binding_bits_signed_bits_get(const void *object)
{
    return ((const BindingBits *)object)->signed_bits;
}

void landin_r440_bindings_binding_bits_signed_bits_set(void *object, int value_)
{
    ((BindingBits *)object)->signed_bits = value_;
}

unsigned int landin_r440_bindings_binding_bits_unsigned_bits_get(const void *object)
{
    return ((const BindingBits *)object)->unsigned_bits;
}

void landin_r440_bindings_binding_bits_unsigned_bits_set(void *object, unsigned int value_)
{
    ((BindingBits *)object)->unsigned_bits = value_;
}

int landin_r440_bindings_binding_bits_neighbour_get(const void *object)
{
    return ((const BindingBits *)object)->neighbour;
}

void landin_r440_bindings_binding_bits_neighbour_set(void *object, int value_)
{
    ((BindingBits *)object)->neighbour = value_;
}

void * landin_r440_bindings_binding_value_allocate(void)
{
    return calloc(1, sizeof(BindingValue));
}

void landin_r440_bindings_binding_value_release(void *object)
{
    free(object);
}

void landin_r440_bindings_binding_value_copy(void *target, const void *source)
{
    *(BindingValue *)target = *(const BindingValue *)source;
}

__SIZE_TYPE__ landin_r440_bindings_binding_value_size(void)
{
    return sizeof(BindingValue);
}

__SIZE_TYPE__ landin_r440_bindings_binding_value_alignment(void)
{
    return _Alignof(BindingValue);
}

int landin_r440_bindings_binding_value_signed_value_get(const void *object)
{
    return ((const BindingValue *)object)->signed_value;
}

void landin_r440_bindings_binding_value_signed_value_set(void *object, int value_)
{
    ((BindingValue *)object)->signed_value = value_;
}

double landin_r440_bindings_binding_value_real_value_get(const void *object)
{
    return ((const BindingValue *)object)->real_value;
}

void landin_r440_bindings_binding_value_real_value_set(void *object, double value_)
{
    ((BindingValue *)object)->real_value = value_;
}

void * landin_r440_bindings_binding_view_allocate(void)
{
    return calloc(1, sizeof(BindingView));
}

void landin_r440_bindings_binding_view_release(void *object)
{
    free(object);
}

void landin_r440_bindings_binding_view_copy(void *target, const void *source)
{
    *(BindingView *)target = *(const BindingView *)source;
}

__SIZE_TYPE__ landin_r440_bindings_binding_view_size(void)
{
    return sizeof(BindingView);
}

__SIZE_TYPE__ landin_r440_bindings_binding_view_alignment(void)
{
    return _Alignof(BindingView);
}

const int * landin_r440_bindings_binding_view_data_get(const void *object)
{
    return ((const BindingView *)object)->data;
}

void landin_r440_bindings_binding_view_data_set(void *object, const int *value_)
{
    ((BindingView *)object)->data = value_;
}

int landin_r440_bindings_binding_view_tag_get(const void *object)
{
    return ((const BindingView *)object)->tag;
}

void landin_r440_bindings_binding_view_tag_set(void *object, int value_)
{
    ((BindingView *)object)->tag = value_;
}

void landin_r440_bindings_binding_borrow_view_call(void *result, const int *argument_1)
{
    *(BindingView *)result = binding_borrow_view(argument_1);
}

int landin_r440_bindings_binding_call_optional_call(const void *argument_1, int argument_2)
{
    return binding_call_optional(((const struct landin_r440_bindings_binding_callback_cell_type *)argument_1)->value, argument_2);
}

void landin_r440_bindings_binding_rotate_value_call(void *result, const void *argument_1)
{
    *(BindingValue *)result = binding_rotate_value(*(const BindingValue *)argument_1);
}

void landin_r440_bindings_binding_select_callback_call(void *result, int argument_1)
{
    ((struct landin_r440_bindings_binding_callback_cell_type *)result)->value = binding_select_callback(argument_1);
}

int * landin_r440_bindings_binding_global_counter_address(void)
{
    return &binding_global_counter;
}

int landin_r440_bindings_binding_global_counter_read(void)
{
    return binding_global_counter;
}

void landin_r440_bindings_binding_global_counter_write(int value_)
{
    binding_global_counter = value_;
}

const int ** landin_r440_bindings_binding_saved_pointer_address(void)
{
    return &binding_saved_pointer;
}

const int * landin_r440_bindings_binding_saved_pointer_read(void)
{
    return binding_saved_pointer;
}

void landin_r440_bindings_binding_saved_pointer_write(const int *value_)
{
    binding_saved_pointer = value_;
}

int * landin_r440_bindings_binding_tls_counter_address(void)
{
    return &binding_tls_counter;
}

int landin_r440_bindings_binding_tls_counter_read(void)
{
    return binding_tls_counter;
}

void landin_r440_bindings_binding_tls_counter_write(int value_)
{
    binding_tls_counter = value_;
}

int binding_receive_many(int fixed_1, ...)
{
    if (fixed_1 != (int)16) __builtin_trap();
    va_list arguments;
    va_start(arguments, fixed_1);
    int tail_1 = va_arg(arguments, int);
    int tail_2 = va_arg(arguments, int);
    int tail_3 = va_arg(arguments, int);
    int tail_4 = va_arg(arguments, int);
    double tail_5 = va_arg(arguments, double);
    double tail_6 = va_arg(arguments, double);
    double tail_7 = va_arg(arguments, double);
    double tail_8 = va_arg(arguments, double);
    double tail_9 = va_arg(arguments, double);
    double tail_10 = va_arg(arguments, double);
    double tail_11 = va_arg(arguments, double);
    double tail_12 = va_arg(arguments, double);
    double tail_13 = va_arg(arguments, double);
    double tail_14 = va_arg(arguments, double);
    long tail_15 = va_arg(arguments, long);
    long tail_16 = va_arg(arguments, long);
    va_end(arguments);
    return landin_binding_receive_handler(fixed_1, tail_1, tail_2, tail_3, tail_4, tail_5, tail_6, tail_7, tail_8, tail_9, tail_10, tail_11, tail_12, tail_13, tail_14, tail_15, tail_16);
}
