/* Generated by bindings/generate.py; do not edit. */
#ifndef LANDIN_R440_BINDINGS_BINDINGS_H
#define LANDIN_R440_BINDINGS_BINDINGS_H

#include "r440-bindings.h"

int landin_binding_receive_handler(int count, int i1, int i2, int i3, int i4, double d1, double d2, double d3, double d4, double d5, double d6, double d7, double d8, double d9, double d10, long l1, long l2);
void * landin_r440_bindings_binding_borrow_callback_cell_allocate(void);
void landin_r440_bindings_binding_borrow_callback_cell_release(void *cell_);
void landin_r440_bindings_binding_borrow_callback_cell_clear(void *cell_);
void landin_r440_bindings_binding_borrow_callback_cell_set(void *cell_, binding_borrow_callback value_);
_Bool landin_r440_bindings_binding_borrow_callback_cell_present(const void *cell_);
binding_borrow_callback landin_r440_bindings_binding_borrow_callback_cell_access(const void *cell_);
_Bool landin_r440_bindings_binding_borrow_callback_cell_invoke(const void *cell_, const int *argument_1, const int **result);
void * landin_r440_bindings_binding_callback_cell_allocate(void);
void landin_r440_bindings_binding_callback_cell_release(void *cell_);
void landin_r440_bindings_binding_callback_cell_clear(void *cell_);
void landin_r440_bindings_binding_callback_cell_set(void *cell_, binding_callback value_);
_Bool landin_r440_bindings_binding_callback_cell_present(const void *cell_);
binding_callback landin_r440_bindings_binding_callback_cell_access(const void *cell_);
_Bool landin_r440_bindings_binding_callback_cell_invoke(const void *cell_, int argument_1, int *result);
void * landin_r440_bindings_binding_bits_allocate(void);
void landin_r440_bindings_binding_bits_release(void *object);
void landin_r440_bindings_binding_bits_copy(void *target, const void *source);
__SIZE_TYPE__ landin_r440_bindings_binding_bits_size(void);
__SIZE_TYPE__ landin_r440_bindings_binding_bits_alignment(void);
int landin_r440_bindings_binding_bits_signed_bits_get(const void *object);
void landin_r440_bindings_binding_bits_signed_bits_set(void *object, int value_);
unsigned int landin_r440_bindings_binding_bits_unsigned_bits_get(const void *object);
void landin_r440_bindings_binding_bits_unsigned_bits_set(void *object, unsigned int value_);
int landin_r440_bindings_binding_bits_neighbour_get(const void *object);
void landin_r440_bindings_binding_bits_neighbour_set(void *object, int value_);
void * landin_r440_bindings_binding_value_allocate(void);
void landin_r440_bindings_binding_value_release(void *object);
void landin_r440_bindings_binding_value_copy(void *target, const void *source);
__SIZE_TYPE__ landin_r440_bindings_binding_value_size(void);
__SIZE_TYPE__ landin_r440_bindings_binding_value_alignment(void);
int landin_r440_bindings_binding_value_signed_value_get(const void *object);
void landin_r440_bindings_binding_value_signed_value_set(void *object, int value_);
double landin_r440_bindings_binding_value_real_value_get(const void *object);
void landin_r440_bindings_binding_value_real_value_set(void *object, double value_);
void * landin_r440_bindings_binding_view_allocate(void);
void landin_r440_bindings_binding_view_release(void *object);
void landin_r440_bindings_binding_view_copy(void *target, const void *source);
__SIZE_TYPE__ landin_r440_bindings_binding_view_size(void);
__SIZE_TYPE__ landin_r440_bindings_binding_view_alignment(void);
const int * landin_r440_bindings_binding_view_data_get(const void *object);
void landin_r440_bindings_binding_view_data_set(void *object, const int *value_);
int landin_r440_bindings_binding_view_tag_get(const void *object);
void landin_r440_bindings_binding_view_tag_set(void *object, int value_);
void landin_r440_bindings_binding_borrow_view_call(void *result, const int *argument_1);
int landin_r440_bindings_binding_call_optional_call(const void *argument_1, int argument_2);
void landin_r440_bindings_binding_rotate_value_call(void *result, const void *argument_1);
void landin_r440_bindings_binding_select_callback_call(void *result, int argument_1);
int * landin_r440_bindings_binding_global_counter_address(void);
int landin_r440_bindings_binding_global_counter_read(void);
void landin_r440_bindings_binding_global_counter_write(int value_);
const int ** landin_r440_bindings_binding_saved_pointer_address(void);
const int * landin_r440_bindings_binding_saved_pointer_read(void);
void landin_r440_bindings_binding_saved_pointer_write(const int *value_);
int * landin_r440_bindings_binding_tls_counter_address(void);
int landin_r440_bindings_binding_tls_counter_read(void);
void landin_r440_bindings_binding_tls_counter_write(int value_);
int binding_receive_many(int fixed_1, ...);

#endif /* LANDIN_R440_BINDINGS_BINDINGS_H */
