[[language]]
name = "landin"
scope = "source.landin"
file-types = ["ldn"]
roots = [".git"]
comment-tokens = ["--"]
block-comment-tokens = { start = "--(", end = ")--" }
indent = { tab-width = 4, unit = "    " }
grammar = "landin"
language-servers = ["refine"]
auto-format = false

[language-server.refine]
command = "refine"
args = ["lsp"]

[[grammar]]
name = "landin"
source = { git = "https://github.com/JanHaan/Landin", rev = "a26f18b891379a68e31e5a87ac5b813cdfa8a943", subpath = "highlight/tree-sitter" }
