# Distinct file URIs for one path retain their own text and diagnostics.
-> {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{}}}
-> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///workspace/alias.ldn","version":1,"languageId":"landin","text":"aa: u8 = 1\n"}}}
-> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file://localhost/workspace/alias.ldn","version":1,"languageId":"landin","text":"bbbb:u8=2\n"}}}
-> {"jsonrpc":"2.0","id":2,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///workspace/alias.ldn"},"options":{"tabSize":4,"insertSpaces":true}}}
-> {"jsonrpc":"2.0","id":3,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file://localhost/workspace/alias.ldn"},"options":{"tabSize":4,"insertSpaces":true}}}
-> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///workspace/alias.ldn","version":2},"contentChanges":[{"text":"cccc:u8=3\n"}]}}
-> {"jsonrpc":"2.0","id":4,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file://localhost/workspace/alias.ldn"},"options":{"tabSize":4,"insertSpaces":true}}}
-> {"jsonrpc":"2.0","id":5,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///workspace/alias.ldn"},"options":{"tabSize":4,"insertSpaces":true}}}
-> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file://localhost/workspace/alias.ldn","version":2},"contentChanges":[{"text":"broken: (u8 =\n"}]}}
-> {"jsonrpc":"2.0","id":6,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///workspace/alias.ldn"},"options":{"tabSize":4,"insertSpaces":true}}}
-> {"jsonrpc":"2.0","method":"textDocument/didClose","params":{"textDocument":{"uri":"file://localhost/workspace/alias.ldn"}}}
-> {"jsonrpc":"2.0","id":7,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///workspace/alias.ldn"},"options":{"tabSize":4,"insertSpaces":true}}}
-> {"jsonrpc":"2.0","id":8,"method":"shutdown","params":{}}
-> {"jsonrpc":"2.0","method":"exit"}
<- {"jsonrpc":"2.0","id":1,"result":{"capabilities":{"positionEncoding":"utf-16","textDocumentSync":{"openClose":true,"change":1},"definitionProvider":true,"hoverProvider":true,"documentFormattingProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix"]}},"serverInfo":{"name":"refine"}}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/alias.ldn","version":1,"diagnostics":[]}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file://localhost/workspace/alias.ldn","version":1,"diagnostics":[]}}
<- {"jsonrpc":"2.0","id":2,"result":[]}
<- {"jsonrpc":"2.0","id":3,"result":[{"range":{"start":{"line":0,"character":5},"end":{"line":0,"character":5}},"newText":" "},{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":7}},"newText":" "},{"range":{"start":{"line":0,"character":8},"end":{"line":0,"character":8}},"newText":" "}]}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/alias.ldn","version":2,"diagnostics":[]}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file://localhost/workspace/alias.ldn","version":1,"diagnostics":[]}}
<- {"jsonrpc":"2.0","id":4,"result":[{"range":{"start":{"line":0,"character":5},"end":{"line":0,"character":5}},"newText":" "},{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":7}},"newText":" "},{"range":{"start":{"line":0,"character":8},"end":{"line":0,"character":8}},"newText":" "}]}
<- {"jsonrpc":"2.0","id":5,"result":[{"range":{"start":{"line":0,"character":5},"end":{"line":0,"character":5}},"newText":" "},{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":7}},"newText":" "},{"range":{"start":{"line":0,"character":8},"end":{"line":0,"character":8}},"newText":" "}]}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/alias.ldn","version":2,"diagnostics":[]}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file://localhost/workspace/alias.ldn","version":2,"diagnostics":[{"range":{"start":{"line":0,"character":11},"end":{"line":0,"character":11}},"severity":1,"code":"L0103","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0103"},"source":"refine","message":"a parameter names its type after `:`\nnote: [1800]: modifiers precede `name: type`","relatedInformation":[{"location":{"uri":"file://localhost/workspace/alias.ldn","range":{"start":{"line":0,"character":9},"end":{"line":0,"character":11}}},"message":"declared here"}]},{"range":{"start":{"line":0,"character":13},"end":{"line":0,"character":13}},"severity":1,"code":"L0103","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0103"},"source":"refine","message":"a signature says what it returns after `->`\nnote: [1800]: signature ::= `(` parameters? `)` `->` returns","relatedInformation":[{"location":{"uri":"file://localhost/workspace/alias.ldn","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":6}}},"message":"declared here"}]},{"range":{"start":{"line":0,"character":13},"end":{"line":0,"character":13}},"severity":1,"code":"L0104","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0104"},"source":"refine","message":"this function is never closed\nnote: [1800]: `=` opens the body and `end` closes it","relatedInformation":[{"location":{"uri":"file://localhost/workspace/alias.ldn","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":6}}},"message":"opened here"}]}]}}
<- {"jsonrpc":"2.0","id":6,"result":[{"range":{"start":{"line":0,"character":5},"end":{"line":0,"character":5}},"newText":" "},{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":7}},"newText":" "},{"range":{"start":{"line":0,"character":8},"end":{"line":0,"character":8}},"newText":" "}]}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file://localhost/workspace/alias.ldn","diagnostics":[]}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/alias.ldn","version":2,"diagnostics":[]}}
<- {"jsonrpc":"2.0","id":7,"result":[{"range":{"start":{"line":0,"character":5},"end":{"line":0,"character":5}},"newText":" "},{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":7}},"newText":" "},{"range":{"start":{"line":0,"character":8},"end":{"line":0,"character":8}},"newText":" "}]}
<- {"jsonrpc":"2.0","id":8,"result":null}
exit: 0
