#!/usr/bin/env python3
"""Reproduce the pinned device fixture projection; not a general CMSIS-SVD generator."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

HERE = Path(__file__).resolve().parent


def require(condition, message):
    if not condition:
        raise ValueError(message)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def encoded(value):
    return (json.dumps(value, indent=2, sort_keys=True) + '\n').encode()


def name(value):
    # Prefix fields and atoms, including vendor names such as EN and null.
    require(re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', value),
            'unsupported vendor identifier: ' + value)
    return value.lower()


def project(root=HERE):
    manifest = json.loads((root / 'fixture.json').read_bytes())
    require(manifest['schema'] == 1, 'fixture schema mismatch')
    for path, expected in manifest['inputs'].items():
        require(digest((root / 'inputs' / path).read_bytes()) == expected,
                'stale or mismatched input: ' + path)
    device = ET.parse(root / 'inputs/RP2040.svd').getroot()
    require(device.findtext('name') == 'RP2040' and
            device.findtext('version') == manifest['svd_version'], 'device identity')
    peripherals = {p.findtext('name'): p for p in device.findall('./peripherals/peripheral')}
    rows = []
    outputs = {}
    for peripheral, selected in manifest['selection'].items():
        instance = peripherals[peripheral]
        base = int(instance.findtext('baseAddress'), 0)
        parent = instance.get('derivedFrom')
        require(parent is None or (peripheral, parent) == ('UART1', 'UART0'),
                'unsupported derivedFrom: ' + peripheral)
        template = peripherals[parent] if parent else instance
        registers = {r.findtext('name'): r for r in template.findall('./registers/register')}
        lines = ['-- Generated by devices/generate.py from the pinned RP2040 SVD.',
                 '-- Copyright (c) 2024 Raspberry Pi Ltd. BSD-3-Clause.',
                 '-- See devices/inputs/LICENSE.pico-sdk and devices/README.md.',
                 '-- Reset metadata performs no initialization. No device RMW is implicit.',
                 'compiler.assert(compiler.byte_order == little)',
                 'compiler.assert(sizeof u32 == 4 and alignof u32 == 4)',
                 f'public base: usize = 0x{base:08x}', '']
        for register in selected:
            element = registers[register]
            key = peripheral + '.' + register
            require(not element.attrib and not any(element.find(t) is not None
                    for t in ('dim', 'cluster', 'alternateRegister', 'alternateGroup')),
                    'unsupported register structure: ' + key)
            def inherited(prop):
                for owner in (element, template, device):
                    value = owner.findtext(prop)
                    if value is not None:
                        return value
                raise ValueError('missing register property: ' + key + '.' + prop)
            width = int(inherited('size'), 0)
            require(width == 32, 'unsupported transaction width: ' + key)
            offset = int(element.findtext('addressOffset'), 0)
            require(offset % 4 == 0 and base + offset <= 0xffffffff, 'address extent')
            row = {'source': key, 'derived_from': parent, 'address': base + offset,
                   'offset': offset, 'width': width, 'alignment': 4,
                   'svd_reset_value': int(inherited('resetValue'), 0),
                   'svd_reset_mask': int(inherited('resetMask'), 0),
                   'register_access': inherited('access'), 'fields': []}
            policy = manifest['policies'][key]
            require(set(policy) <= {'read', 'write', 'reserved', 'write_mask'}, 'unknown policy')
            require(policy['read'] in ('normal', 'modify', 'refused') and
                    policy['write'] in ('normal', 'one_clears', 'refused') and
                    policy['reserved'] in ('zero', 'preserve'), 'unsupported access policy')
            row['policy'] = policy
            reg = name(register)
            mask = 0
            fields = []
            seen = set()
            for field in element.findall('./fields/field'):
                require(not field.attrib, 'unsupported field inheritance')
                field_name = field.findtext('name')
                spelling = 'f_' + name(field_name)
                require(spelling not in seen, 'normalized field collision')
                seen.add(spelling)
                bounds = re.fullmatch(r'\[(\d+):(\d+)\]', field.findtext('bitRange', ''))
                require(bounds is not None, 'unsupported bit range')
                high, low = map(int, bounds.groups())
                require(0 <= low <= high < 32, 'invalid field extent')
                bits = ((1 << (high-low+1))-1) << low
                require(mask & bits == 0, 'overlapping fields')
                mask |= bits
                values = [(v.findtext('name'), int(v.findtext('value'), 0))
                          for v in field.findall('./enumeratedValues/enumeratedValue')]
                require(len(set(v for _, v in values)) == len(values), 'duplicate encoding')
                require(all(0 <= v < 1 << (high-low+1) for _, v in values), 'encoding extent')
                field_row = {'name': field_name, 'low': low, 'high': high,
                             'mask': bits, 'access': field.findtext('access', inherited('access')),
                             'read_action': field.findtext('readAction'),
                             'modified_write': field.findtext('modifiedWriteValues'),
                             'encodings': values}
                numeric = key + '.' + field_name in manifest['numeric_enums']
                field_row['representation'] = 'unsigned' if numeric or not values else 'encoded'
                row['fields'].append(field_row)
                typ = 'u' + str(high-low+1)
                if values and not numeric:
                    typ = reg + '_' + name(field_name) + '_value'
                    atoms = [(reg+'_'+name(field_name)+'_'+name(n), v) for n, v in values]
                    require(len({n for n, _ in atoms}) == len(atoms), 'normalized enum collision')
                    lines.extend('public '+n+': atom' for n, _ in atoms)
                    lines.append('public '+typ+': type = u'+str(high-low+1)+' ('+
                                 ' | '.join(n+' = '+str(v) for n, v in atoms)+')')
                fields.append(f'    {spelling}: {typ} at {low}..{high}')
            require(fields, 'selected register has no fields')
            row['named_mask'] = mask
            # The SVD claims full reset knowledge by device inheritance even
            # for reserved bits and the UART FIFO. Keep that claim separately;
            # the reviewed fixture promises only named, documented reset bits.
            row['known_reset_mask'] = int(manifest['reset_mask_overrides'].get(
                key, str(mask & row['svd_reset_mask'])), 0)
            require(row['known_reset_mask'] & ~mask == 0, 'reset knowledge outside named fields')
            row['known_reset_value'] = row['svd_reset_value'] & row['known_reset_mask']
            lines += [f'public {reg}_offset: usize = 0x{offset:x}',
                      f'public {reg}_address: usize = 0x{base+offset:08x}',
                      f'public {reg}_named_mask: u32 = 0x{mask:08x}',
                      f'public {reg}_reset_mask: u32 = 0x{row["known_reset_mask"]:08x}',
                      f'public {reg}_reset_value: u32 = 0x{row["known_reset_value"]:08x}',
                      f'public {reg}_image: type = layout(packed, u32) struct',
                      *fields, f'end {reg}_image', '',
                      f'public {reg}_decode: (raw: u32) -> (image: {reg}_image) =',
                      '    image = zeroed',
                      '    bits: ptr mut u32 = ptr(usize(addr image))',
                      '    bits.val = raw', f'end {reg}_decode', '',
                      f'public {reg}_encode: (image: {reg}_image) -> (raw: u32) =',
                      '    bits: ptr u32 = ptr(usize(addr image))',
                      '    raw = bits.val', f'end {reg}_encode', '']
            if policy['read'] != 'refused':
                # modify is FIFO consumption, not clear-on-read. The scalar
                # primitive preserves exactly one read without that false claim.
                operation = ('compiler.volatile_load(port)' if policy['read'] == 'modify'
                             else 'compiler.register_read(port, compiler.normal_read)')
                lines += [f'public {reg}_read: (device_base: usize) -> (raw: u32) =',
                          f'    port: ptr u32 = ptr(device_base + {reg}_offset)',
                          '    raw = '+operation, f'end {reg}_read', '']
            if policy['write'] != 'refused':
                write_mask = int(policy.get('write_mask', str(mask)), 0)
                require(write_mask & ~mask == 0, 'write mask outside selected fields')
                mode = 'one_clears' if policy['write'] == 'one_clears' else 'normal_write'
                reserved = 'write_zero' if policy['reserved'] == 'zero' else 'preserve'
                lines += [f'public {reg}_write: (device_base: usize, raw: u32) -> none =',
                          f'    port: ptr mut u32 = ptr(device_base + {reg}_offset)',
                          f'    compiler.register_write(port, raw, compiler.{mode},',
                          f'                            compiler.{reserved}, 0x{write_mask:08x})',
                          f'end {reg}_write', '']
            rows.append(row)
        outputs['rp2040/' + name(peripheral) + '/device.ldn'] = ('\n'.join(lines)).encode()
    outputs['correspondence.json'] = encoded(rows)
    return outputs


def verify(directory, outputs):
    actual = {str(p.relative_to(directory)): p.read_bytes()
              for p in directory.rglob('*') if p.is_file()}
    require(actual.keys() == outputs.keys(), 'stale generated file inventory')
    for path, data in outputs.items():
        require(actual[path] == data, 'stale generated output: '+path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--inputs', type=Path, default=HERE,
                        help='directory containing fixture.json and inputs/')
    parser.add_argument('--output', type=Path,
                        help='new output directory; omitted verifies checked-in bytes')
    args = parser.parse_args()
    outputs = project(args.inputs)
    hashes = encoded({name: digest(data) for name, data in sorted(outputs.items())})
    outputs['outputs.json'] = hashes
    if args.output:
        args.output.mkdir(parents=True, exist_ok=False)
        for path, data in outputs.items():
            dest = args.output / path
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)
    else:
        verify(HERE / 'generated', outputs)
    print('device fixture projection verified: '+str(len(outputs))+' files')


if __name__ == '__main__':
    main()
