#!/usr/bin/env python3
"""Independent vendor-header/literal oracles and fresh-input refusal controls."""
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

from generate import HERE, digest, project, verify


class Fixtures(unittest.TestCase):
    def test_vendor_headers(self):
        # These separately shipped official C headers are not generated by
        # our SVD projection. Every selected register and field is compared.
        rows = json.loads(project()['correspondence.json'])
        bases = {'IO_BANK0': 0x40014000, 'SIO': 0xd0000000,
                 'TIMER': 0x40054000, 'UART0': 0x40034000,
                 'UART1': 0x40038000, 'DMA': 0x50000000}
        for row in rows:
            peripheral, register = row['source'].split('.')
            family = 'UART' if peripheral.startswith('UART') else peripheral
            text = (HERE / 'inputs' / (family.lower()+'.h')).read_text()
            macros = dict(re.findall(r'^#define (\w+)\s+_u\((0x[0-9a-fA-F]+|[0-9]+)\)',
                                     text, re.MULTILINE))
            prefix = family+'_'+register
            with self.subTest(register=row['source']):
                self.assertEqual(row['offset'], int(macros[prefix+'_OFFSET'], 0))
                self.assertEqual(row['address'], bases[peripheral]+row['offset'])
                self.assertEqual(row['width'], 32)
                self.assertEqual(row['alignment'], 4)
                self.assertEqual(row['named_mask'], int(macros[prefix+'_BITS'], 0))
                reset_mask = 0
                reset_value = 0
                for field in row['fields']:
                    # Single-field registers omit a second repeated suffix.
                    field_prefix = prefix if field['name'] == register else prefix+'_'+field['name']
                    self.assertEqual(field['mask'], int(macros[field_prefix+'_BITS'], 0))
                    self.assertEqual(field['low'], int(macros[field_prefix+'_LSB'], 0))
                    self.assertEqual(field['high'], int(macros[field_prefix+'_MSB'], 0))
                    access = re.search(r'^#define '+field_prefix+r'_ACCESS\s+"(.*?)"',
                                       text, re.MULTILINE).group(1)
                    self.assertEqual((field['access'], field['read_action'],
                                      field['modified_write']), {
                        'RW': ('read-write', None, None),
                        'RO': ('read-only', None, None),
                        'WO': ('write-only', None, None),
                        'WC': ('read-write', None, 'oneToClear'),
                        'RWF': ('read-write', 'modify', None),
                    }[access])
                    reset = macros.get(field_prefix+'_RESET')
                    if reset is not None:
                        reset_mask |= field['mask']
                        reset_value |= int(reset, 0) << field['low']
                    else:
                        self.assertRegex(text, r'#define '+field_prefix+r'_RESET\s+"-"')
                    for name, value in field['encodings']:
                        if field['name'] == 'TREQ_SEL':
                            # Header supplies geometry but not DREQ names.
                            # The literal request table below is independent.
                            requests = ([f'PIO{p}_{d}{n}' for p in range(2)
                                         for d in ('TX','RX') for n in range(4)] +
                                        ['SPI0_TX','SPI0_RX','SPI1_TX','SPI1_RX',
                                         'UART0_TX','UART0_RX','UART1_TX','UART1_RX'] +
                                        ['PWM_WRAP'+str(n) for n in range(8)] +
                                        ['I2C0_TX','I2C0_RX','I2C1_TX','I2C1_RX','ADC','XIP_STREAM',
                                         'XIP_SSITX','XIP_SSIRX'])
                            expected = dict(zip(requests, range(40)))
                            expected.update(TIMER0=59,TIMER1=60,TIMER2=61,TIMER3=62,PERMANENT=63)
                            self.assertEqual(value, expected[name])
                        else:
                            self.assertEqual(value, int(macros[field_prefix+'_VALUE_'+name.upper()], 0))
                self.assertEqual(row['known_reset_mask'], reset_mask)
                self.assertEqual(row['known_reset_value'], reset_value)

    def test_literal_contract(self):
        rows = {r['source']: r for r in json.loads(project()['correspondence.json'])}
        self.assertEqual(len(rows), 30)
        self.assertEqual(rows['UART1.UARTFR']['derived_from'], 'UART0')
        self.assertEqual(rows['DMA.CH1_CTRL_TRIG']['offset'] - rows['DMA.CH0_CTRL_TRIG']['offset'], 64)
        self.assertEqual(rows['IO_BANK0.GPIO1_CTRL']['offset'] - rows['IO_BANK0.GPIO0_CTRL']['offset'], 8)
        self.assertEqual([rows['TIMER.ALARM'+str(i)]['offset'] for i in range(4)], [16,20,24,28])
        self.assertEqual(rows['DMA.CH0_AL1_CTRL']['svd_reset_mask'], 0)
        self.assertEqual(rows['DMA.CH0_AL1_CTRL']['known_reset_mask'], 0)
        self.assertEqual(rows['UART0.UARTDR']['known_reset_mask'], 0)
        self.assertEqual(rows['UART0.UARTFR']['known_reset_value'], 0x90)
        self.assertEqual(rows['IO_BANK0.GPIO0_CTRL']['named_mask'], 0x3003331f)
        for key in ('DMA.CH0_CTRL_TRIG', 'DMA.CH1_CTRL_TRIG'):
            fields = {f['name']: f for f in rows[key]['fields']}
            self.assertEqual(fields['DATA_SIZE']['encodings'],
                             [['SIZE_BYTE',0],['SIZE_HALFWORD',1],['SIZE_WORD',2]])
            self.assertEqual(fields['RING_SIZE']['representation'], 'unsigned')
            self.assertEqual(fields['RING_SIZE']['mask'], 0x3c0)
        self.assertEqual(rows['UART0.UARTRSR']['policy']['write'], 'refused')
        self.assertEqual(rows['UART0.UARTDR']['policy']['read'], 'modify')
        self.assertEqual(rows['UART0.UARTFR']['policy']['write'], 'refused')
        self.assertEqual(rows['SIO.GPIO_OUT_SET']['policy']['read'], 'refused')
        self.assertEqual(rows['TIMER.INTR']['policy']['write'], 'one_clears')
        # Independent reviewed policy oracle: no manifest values are used to
        # construct the expected access surface or restricted write masks.
        for key, row in rows.items():
            read = ('refused' if key in {'SIO.GPIO_OUT_SET', 'SIO.GPIO_OUT_CLR',
                    'UART0.UARTICR'} else 'modify' if key == 'UART0.UARTDR' else 'normal')
            write = ('refused' if key in {'SIO.GPIO_IN', 'TIMER.TIMERAWL',
                     'UART0.UARTRSR', 'UART0.UARTFR', 'UART1.UARTFR', 'DMA.CH0_AL1_CTRL'}
                     else 'one_clears' if key in {'TIMER.INTR', 'DMA.INTR', 'UART0.UARTICR'}
                     else 'normal')
            expected = {'read': read, 'write': write,
                        'reserved': 'preserve' if key == 'SIO.GPIO_OUT' else 'zero'}
            if key == 'UART0.UARTDR':
                expected['write_mask'] = '0x000000ff'
            if key in {'DMA.CH0_CTRL_TRIG', 'DMA.CH1_CTRL_TRIG'}:
                expected['write_mask'] = '0x00ffffff'
            self.assertEqual(row['policy'], expected, key)

    def test_fresh_and_stale(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            copies = []
            for n in range(2):
                inputs = root / ('input-'+str(n))
                inputs.mkdir()
                shutil.copytree(HERE / 'inputs', inputs / 'inputs')
                shutil.copyfile(HERE / 'fixture.json', inputs / 'fixture.json')
                output = root / ('output-'+str(n))
                subprocess.run([sys.executable, str(HERE / 'generate.py'),
                    '--inputs', str(inputs), '--output', str(output)], check=True,
                    stdout=subprocess.PIPE, timeout=20)
                copies.append({str(p.relative_to(output)): p.read_bytes()
                               for p in output.rglob('*') if p.is_file()})
            self.assertEqual(copies[0], copies[1])
            checked = {str(p.relative_to(HERE/'generated')): p.read_bytes()
                       for p in (HERE/'generated').rglob('*') if p.is_file()}
            self.assertEqual(copies[0], checked)
            verify(output, copies[0])
            stale = output / 'rp2040/uart0/device.ldn'
            stale.write_bytes(stale.read_bytes()+b'-- stale\n')
            with self.assertRaisesRegex(ValueError, 'stale generated output: rp2040/uart0/device.ldn'):
                verify(output, copies[0])
            stale.unlink()
            with self.assertRaisesRegex(ValueError, 'stale generated file inventory'):
                verify(output, copies[0])
            (inputs / 'inputs/RP2040.svd').write_bytes(b'<stale/>')
            with self.assertRaisesRegex(ValueError, 'stale or mismatched input: RP2040.svd'):
                project(inputs)
            # Rehashing an unsupported shape is not enough to admit it.
            original = (HERE/'inputs/RP2040.svd').read_bytes()
            for old, new, message in (
                (b'<name>GPIO0_CTRL</name>', b'<name>GPIO0_CTRL</name><dim>2</dim>', 'unsupported register structure'),
                (b'<size>32</size>', b'<size>64</size>', 'unsupported transaction width'),
                (b'<name>GPIO0_CTRL</name>', b'<name>GPIO0_CTRL</name><size>64</size>', 'unsupported transaction width'),
            ):
                data = original.replace(old, new, 1)
                self.assertNotEqual(data, original)
                (inputs/'inputs/RP2040.svd').write_bytes(data)
                manifest = json.loads((HERE/'fixture.json').read_bytes())
                manifest['inputs']['RP2040.svd'] = digest(data)
                (inputs/'fixture.json').write_text(json.dumps(manifest))
                with self.assertRaisesRegex(ValueError, message):
                    project(inputs)


if __name__ == '__main__':
    unittest.main()
