# A diagnostic, navigation request, hover range and returned edits after
# a two-byte character and one outside the basic plane, counted in the
# negotiated UTF-16 units (the default).
-> {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{}}}
-> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///workspace/e.ldn","languageId":"landin","version":1,"text":"f: (x: u8) -> (y: u8) =\n    -- caf\u00e9 \ud834\udd1e\n    y = x + \"\u00e9\ud834\udd1e\" + true\nend f\n"}}}
# The Unicode string precedes the selected name and formatting edit.
-> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///workspace/navigation/main.ldn","languageId":"landin","version":1,"text":"choose: (label: []u8, count: u32) -> (result: u32) =\n    result = count\nend choose\n\nf: (count: u32) -> (result: u32) =\n    result = choose (\"\u00e9\ud834\udd1e\",  count)\nend f\n"}}}
-> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///workspace/fixes/main.ldn","languageId":"landin","version":1,"text":"choose: (label: []u8, count: u32) -> (result: u32) =\n    result = count\nend choose\n\nf: (count: u32) -> (result: u32) =\n    result = choose (\"\u00e9\ud834\udd1e\",  cuont)\nend f\n"}}}
pause
-> {"jsonrpc":"2.0","id":3,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///workspace/navigation/main.ldn"},"position":{"line":5,"character":29}}}
-> {"jsonrpc":"2.0","id":4,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///workspace/navigation/main.ldn"},"position":{"line":5,"character":29}}}
-> {"jsonrpc":"2.0","id":5,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///workspace/navigation/main.ldn"},"options":{"tabSize":4,"insertSpaces":true}}}
-> {"jsonrpc":"2.0","id":6,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///workspace/fixes/main.ldn"},"range":{"start":{"line":5,"character":29},"end":{"line":5,"character":29}},"context":{"diagnostics":[]}}}
-> {"jsonrpc":"2.0","id":2,"method":"shutdown"}
-> {"jsonrpc":"2.0","method":"exit"}
<- {"jsonrpc":"2.0","id":1,"result":{"capabilities":{"positionEncoding":"utf-16","textDocumentSync":{"openClose":true,"change":2},"definitionProvider":true,"hoverProvider":true,"documentFormattingProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix"]}},"serverInfo":{"name":"refine"}}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/e.ldn","version":1,"diagnostics":[{"range":{"start":{"line":2,"character":12},"end":{"line":2,"character":17}},"severity":1,"code":"L0301","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0301"},"source":"refine","message":"a text literal cannot take the `u8` context required here\nnote: [0260]: a text literal takes one of the text views, including `[]u8`","relatedInformation":[{"location":{"uri":"file:///workspace/e.ldn","range":{"start":{"line":2,"character":8},"end":{"line":2,"character":17}}},"message":"required by this operator"}]},{"range":{"start":{"line":2,"character":20},"end":{"line":2,"character":24}},"severity":1,"code":"L0301","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0301"},"source":"refine","message":"this is `bool` and `u8` belongs here\nnote: [1890]: two types that must agree, and [0310] converts nothing between them","relatedInformation":[{"location":{"uri":"file:///workspace/e.ldn","range":{"start":{"line":2,"character":8},"end":{"line":2,"character":24}}},"message":"required by this operator"}]}]}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/fixes/main.ldn","version":1,"diagnostics":[{"range":{"start":{"line":5,"character":29},"end":{"line":5,"character":34}},"severity":1,"code":"L0201","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0201"},"source":"refine","message":"`cuont` is not declared in any scope this reaches\nnote: [1860]: a name that is not in scope is a misspelling, not a new binding"}]}}
<- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///workspace/navigation/main.ldn","version":1,"diagnostics":[]}}
<- {"jsonrpc":"2.0","id":3,"result":{"uri":"file:///workspace/navigation/main.ldn","range":{"start":{"line":4,"character":4},"end":{"line":4,"character":9}}}}
<- {"jsonrpc":"2.0","id":4,"result":{"contents":{"kind":"markdown","value":"```landin\ncount: u32\n```"},"range":{"start":{"line":5,"character":29},"end":{"line":5,"character":34}}}}
<- {"jsonrpc":"2.0","id":5,"result":[{"range":{"start":{"line":5,"character":19},"end":{"line":5,"character":20}},"newText":""},{"range":{"start":{"line":5,"character":27},"end":{"line":5,"character":29}},"newText":" "}]}
<- {"jsonrpc":"2.0","id":6,"result":[{"title":"did you mean `count`?","kind":"quickfix","diagnostics":[{"range":{"start":{"line":5,"character":29},"end":{"line":5,"character":34}},"severity":1,"code":"L0201","codeDescription":{"href":"https://www.701.dev/diagnostics.html#l0201"},"source":"refine","message":"`cuont` is not declared in any scope this reaches\nnote: [1860]: a name that is not in scope is a misspelling, not a new binding"}],"isPreferred":false,"edit":{"changes":{"file:///workspace/fixes/main.ldn":[{"range":{"start":{"line":5,"character":29},"end":{"line":5,"character":34}},"newText":"count"}]}}}]}
<- {"jsonrpc":"2.0","id":2,"result":null}
exit: 0
