id = "landin"
name = "Landin"
description = "Landin language support"
version = "0.0.0"
schema_version = 1
authors = ["Landin contributors"]
repository = "https://github.com/JanHaan/Landin"

[grammars.landin]
repository = "https://github.com/JanHaan/Landin"
rev = "22e994a35c92d4a0b52fb64fcab27e6792a5e331"
path = "highlight/tree-sitter"

[language_servers.refine]
name = "refine"
languages = ["Landin"]
