id = "landin"
name = "Landin"
description = "Landin language support"
version = "0.0.0"
schema_version = 1
authors = ["Landin contributors"]
repository = "https://github.com/JanHaan/Landin"

[grammars.landin]
repository = "https://github.com/JanHaan/Landin"
rev = "8f25c49ea5a9c46b0949c9c01d69208a14c447c3"
path = "highlight/tree-sitter"

[language_servers.refine]
name = "refine"
languages = ["Landin"]
