--  Generated by check.py from docs/diagnostics.md.  Do not edit;
--  regenerate with python3 check.py --catalogue.

package body Landin.Diagnostics.Explanations is

   LF : constant Character := Character'Val (10);

   function Explanation (Of_Code : Catalogue.Code_Name) return String
     is (case Of_Code is
            when Catalogue.No_Frontend =>
               "Retired. A source was read and no frontend was wired to "
               & "the driver. The frontend has been wired since the first "
               & "executable slice, so nothing raises this and the number "
               & "is kept so no other rule can take it.",
            when Catalogue.Unknown_Option =>
               "The command line asked for something the driver does not"
               & " define: an unknown option, an option without its value "
               & "or repeated where it may not be, or a combination the dr"
               & "iver refuses, such as `--emit` with no source, an output"
               & " that would overwrite a source or another output, or `re"
               & "fine explain` with a code no catalogue row holds. `refin"
               & "e --help` lists the options. The status is 2, which says"
               & " the request and not a program was wrong.",
            when Catalogue.Unreadable_Source =>
               "A source named on the command line is missing or cannot "
               & "be read. Check the path and its permissions.",
            when Catalogue.Unknown_Target =>
               "`--target=` names no target the compiler describes. `ref"
               & "ine --identify` lists the described targets.",
            when Catalogue.Unwritable_Output =>
               "An output file cannot be written: its directory is missi"
               & "ng or read-only. Choose another path with `-o`.",
            when Catalogue.Module_Not_Found =>
               "No import root holds the module an import names [1420]. "
               & "Roots are searched in the order `--root=` gives them, an"
               & "d a path's segments are directories under a root, spelle"
               & "d exactly. When a directory near the missing segment is "
               & "there, the diagnostic offers it as a likely fix.",
            when Catalogue.Module_Directory_Invalid =>
               "With `--root=`, the entry module is a directory [1410], "
               & "and the operand given is not a readable one. Pass the di"
               & "rectory, not a file inside it.",
            when Catalogue.Construct_Not_Enabled =>
               "The program uses a construct the tour describes and the "
               & "kernel does not enable yet [1830]. The two notes name th"
               & "e tour paragraph and whether the form is a recorded boun"
               & "dary, withdrawn with a replacement, or transferred to la"
               & "ter work. Write the program without it, or with what the"
               & " note says replaces it.",
            when Catalogue.Malformed_Integer =>
               "An integer literal has a digit its base does not have, o"
               & "r runs straight into a name [1770]. `0x` takes hexadecim"
               & "al digits, `0b` binary and `0o` octal, and a literal nee"
               & "ds a separator before a following name.",
            when Catalogue.Unknown_Bytes =>
               "A run of bytes no lexical rule spells [1750]. A name is "
               & "lower case [1760], and a byte outside the source alphabe"
               & "t belongs in a text literal.",
            when Catalogue.Unterminated_Comment =>
               "A block comment that is never closed [1780]. Every opene"
               & "r needs its closer; the second label shows where the com"
               & "ment began.",
            when Catalogue.Unterminated_Literal =>
               "A quoted literal that is never closed on its line [0260]"
               & ". Close it, or write a raw literal for text that spans l"
               & "ines [0280].",
            when Catalogue.Name_Expected =>
               "A name belongs here and something else stands there [176"
               & "0]. A keyword is never a name, including a control word "
               & "in any position (D225), and `_` alone is the discard. Ch"
               & "oose another name, such as `begin_value` for `begin`.",
            when Catalogue.Type_Expected =>
               "A type position holds nothing the kernel enables as a ty"
               & "pe [1790].",
            when Catalogue.Expression_Expected =>
               "An expression was required and none begins here [1820]: "
               & "an operator with no operand, or a separator where a valu"
               & "e belongs.",
            when Catalogue.Token_Expected =>
               "A token the grammar requires is absent [1810]. The secon"
               & "d label points at the construct that required it. When a"
               & " name near the required keyword stands in its place, suc"
               & "h as `thne` for `then`, the diagnostic offers the keywor"
               & "d as a likely fix.",
            when Catalogue.Unclosed_Construct =>
               "A construct opened and its `end` never arrived [1800]. T"
               & "he second label shows where it opened; close it there.",
            when Catalogue.Assignment_In_Expression =>
               "Assignment is a statement and never an expression [0390]"
               & ". `==` compares. When the assignment is an `=`, the diag"
               & "nostic offers `==` as a likely fix.",
            when Catalogue.Comparison_Chained =>
               "A comparison takes at most one operator [1820]: `a < b <"
               & " c` compares a `bool` with `c`. Write `a < b and b < c`.",
            when Catalogue.Return_Carries_Value =>
               "`return` carries no value [1810]. Assign the named retur"
               & "n, then `return`.",
            when Catalogue.Public_On_Statement =>
               "`public` belongs on a module declaration and never on a "
               & "statement [1740].",
            when Catalogue.End_Name_Mismatch =>
               "The name after `end` must be the name of what it closes "
               & "[1800], or be absent where the construct allows that. Th"
               & "e diagnostic offers the declared name as an exact fix.",
            when Catalogue.Stray_Token =>
               "A run of tokens begins no declaration or statement [1740"
               & "]. Often a keyword used as a name (D225), or a line left"
               & " from an edit.",
            when Catalogue.Nesting_Too_Deep =>
               "An implementation limit, not a rule of the language: a c"
               & "onstruct nests more deeply than the parser holds. Split "
               & "the expression or the block into named parts.",
            when Catalogue.Positional_After_Named =>
               "A positional argument follows a named one [0980]. Every "
               & "positional argument comes first.",
            when Catalogue.Duplicate_Declaration =>
               "One scope gives one name to one thing [1850]. Two declar"
               & "ations of one name in one scope, or two imports with one"
               & " final segment, are refused, and the second label shows "
               & "the first. An inner scope may shadow an outer name; that"
               & " is not this.",
            when Catalogue.Unresolved_Name =>
               "A name that is declared in no scope this use reaches [18"
               & "60]. There is no implicit declaration, so it is a misspe"
               & "lling or a name used outside its scope. When a declared "
               & "name the position could mean is near it, the diagnostic "
               & "offers that name as a likely fix: a local or parameter, "
               & "a type, a public member of an imported module, never a n"
               & "ame out of scope or inaccessible.",
            when Catalogue.Inaccessible_Name =>
               "A declaration of another module is used and it is not `p"
               & "ublic` [1410]. The second label shows the declaration. M"
               & "ake it `public` in its module, or use something that mod"
               & "ule does export.",
            when Catalogue.Reserved_Tool_Name =>
               "A tool namespace, `compiler`, `assembler` or `linker`, i"
               & "s bound or used in a way it does not allow [1560] (D202)"
               & ". Those three are in scope without an import and cannot "
               & "be imported, rebound or given a member they do not have.",
            when Catalogue.Literal_Out_Of_Range =>
               "A value known at compile time does not fit the type its "
               & "context gives it [1880], or the target cannot hold it. W"
               & "rite a smaller value or give the context a wider type.",
            when Catalogue.Type_Mismatch =>
               "Two types that must agree do not [1890]. The second labe"
               & "l shows where the requirement was stated. When the disag"
               & "reement is a named argument no parameter carries [0980],"
               & " the diagnostic offers the parameter label near it as a "
               & "likely fix.",
            when Catalogue.Not_Definitely_Assigned =>
               "A name is read on a path that does not assign it first ["
               & "1910]. Assign it on every path before the read, or give "
               & "it a value where it is declared.",
            when Catalogue.Immutable_Target =>
               "A place that may not be written [1900]: an immutable bin"
               & "ding, an `in` parameter, an atom, a function, or storage"
               & " reached through a read-only reference. When the place i"
               & "s a local or module binding of one name, the diagnostic "
               & "offers `mut` on its declaration as a likely fix.",
            when Catalogue.Unsupported_Use =>
               "A name used in a way the kernel does not enable [1920], "
               & "found once the checker knows what the name is. The two n"
               & "otes are [1830]'s: the tour paragraph and the form's sta"
               & "nding.",
            when Catalogue.Not_Known_At_Compile_Time =>
               "A value required before the program runs, which the comp"
               & "iler's closed fold cannot produce [1940] (D136): a modul"
               & "e value or an array bound that names a runtime value, ca"
               & "lls a function, or depends on itself.",
            when Catalogue.Impossible_Operand =>
               "An operand the operation cannot take, where the compiler"
               & " knows it [1950]: a divisor of zero, a shift by a negati"
               & "ve amount, an index outside a fixed array, or a range su"
               & "btype whose bounds are reversed.",
            when Catalogue.Compile_Time_Assertion_Failed =>
               "A compile-time assertion is false [1510].",
            when Catalogue.Cyclic_Type_Alias =>
               "A chain of type aliases that never reaches a type [1795]"
               & ".",
            when Catalogue.Unresolved_Field =>
               "A field a struct, a variant case or a result was not dec"
               & "lared with [0750] [0990]. When a declared field is near "
               & "the written name, the diagnostic offers it as a likely f"
               & "ix.",
            when Catalogue.Field_Named_Twice =>
               "A struct literal or a struct names a field more than onc"
               & "e [0710].",
            when Catalogue.Field_Not_Given =>
               "A struct literal gives no value for a field and no `of` "
               & "covers it [0710].",
            when Catalogue.Variant_Case_Named_Twice =>
               "A match names one variant case twice [1210].",
            when Catalogue.Variant_Case_Not_Matched =>
               "An exhaustive match does not name every case [1210]. Add"
               & " the missing arms, or an `else` arm.",
            when Catalogue.Recursive_Nominal_Value =>
               "A struct holds itself by value, so its layout could neve"
               & "r be finite (D137). Hold it through a pointer.",
            when Catalogue.Reference_Escapes =>
               "A reference is kept past the storage it points into [077"
               & "0] [0780]: the address of a local returned, or stored wh"
               & "ere the local cannot outlive it.",
            when Catalogue.Borrowed_Place =>
               "A place is changed while a view derived from it is still"
               & " in use [0800] [0830]. Finish with the view first, or ta"
               & "ke it again after the change.",
            when Catalogue.Return_Sources_Disagree =>
               "A returned reference must derive from exactly the parame"
               & "ters its `from` names [0790]. Name the source, or return"
               & " something derived from it.",
            when Catalogue.Conformance_Collision =>
               "Two conformances of one type to one concept [1280]. Ther"
               & "e is one register for the whole program; remove one, or "
               & "give one type `distinct` identity.",
            when Catalogue.Unsatisfied_Constraint =>
               "A type given for a formal lacks a conformance the formal"
               & " requires [1290].",
            when Catalogue.Compiler_Conformance_Reserved =>
               "The compiler owns `zeroable` and its conformances; a pro"
               & "gram declares neither.",
            when Catalogue.Malformed_Text_Literal =>
               "A text literal holds an escape the language does not def"
               & "ine, or bytes that are not UTF-8 [0270] [1750].",
            when Catalogue.Malformed_Float_Literal =>
               "A float literal needs its fraction, and an exponent wher"
               & "e its form requires one [0210] [0220] [0230].",
            when Catalogue.Malformed_Character_Literal =>
               "A character literal holds exactly one Unicode scalar val"
               & "ue [0250] [0270].",
            when Catalogue.Malformed_Raw_Literal =>
               "A raw literal's content is UTF-8, and each line that is "
               & "not blank starts with the closing delimiter's indentatio"
               & "n [0280] [1750].",
            when Catalogue.Size_Limit_Exceeded =>
               "An implementation limit, not a rule of the language: a r"
               & "outine declares, or a struct holds, more than the compil"
               & "er admits (D247). Split it.",
            when Catalogue.Mutable_Never_Written =>
               "A warning, and the program is accepted: a local binding "
               & "is declared `mut` and nothing writes it, steps it, passe"
               & "s it `inout` or takes a mutable view of it. Without `mut"
               & "` it means the same, so the diagnostic offers removing t"
               & "he word as an exact fix. The language permits the `mut`;"
               & " the warning is the compiler's judgement and not a rule "
               & "(D251). A shared declaration is warned about only when n"
               & "one of its names is written, and a module binding never "
               & "is, since a linked routine or a debugger may write it.",
            when Catalogue.No_Toolchain =>
               "No assembler and linker for the selected target were fou"
               & "nd on this host [1550]. The note names the program looke"
               & "d for; `--toolchain=` names another.",
            when Catalogue.Toolchain_Failed =>
               "The platform assembler or linker refused what the compil"
               & "er emitted [1550]. The tool's own output follows the dia"
               & "gnostic.",
            when Catalogue.Entry_Point_Missing =>
               "`--emit=exe` needs an entry: a hosted `main` of the one "
               & "shape [1970] in the entry module, or the firmware routin"
               & "e `--firmware-entry=` names.",
            when Catalogue.Argument_Not_In_A_Register =>
               "Retired. An internal call could only pass arguments in r"
               & "egisters. The internal calling convention now places eve"
               & "ry argument after the sixth on the stack, so nothing rai"
               & "ses this.",
            when Catalogue.Frame_Not_Addressable =>
               "A verified frame is larger than x86-64's signed 32-bit d"
               & "isplacement reaches. Move the large local storage into a"
               & " module value or an allocation.",
            when Catalogue.Image_Materialization_Limit =>
               "Firmware static images exceed what the assembler is give"
               & "n to materialize [1640]. Make the static data smaller, o"
               & "r hold it in fewer, larger values.",
            when Catalogue.Panic_Contract_Invalid =>
               "The panic handler is invalid, or the program has more ch"
               & "eck sites than their identifier space holds [1670].");

   function Example (Of_Code : Catalogue.Code_Name) return String
     is (case Of_Code is
            when Catalogue.No_Frontend =>
               "",
            when Catalogue.Unknown_Option =>
               "",
            when Catalogue.Unreadable_Source =>
               "",
            when Catalogue.Unknown_Target =>
               "",
            when Catalogue.Unwritable_Output =>
               "",
            when Catalogue.Module_Not_Found =>
               "",
            when Catalogue.Module_Directory_Invalid =>
               "",
            when Catalogue.Construct_Not_Enabled =>
               "point: type = struct"
               & LF
               & "    x: i32"
               & LF
               & "end point"
               & LF
               & LF
               & "state: point = point(of zeroed)"
               & LF,
            when Catalogue.Malformed_Integer =>
               "mask: u64 = 1u64"
               & LF,
            when Catalogue.Unknown_Bytes =>
               "X: u32 = 1"
               & LF,
            when Catalogue.Unterminated_Comment =>
               "--( this one never closes"
               & LF
               & "f: () -> (r: i32) = 1 end"
               & LF,
            when Catalogue.Unterminated_Literal =>
               "value := ""never closed"
               & LF,
            when Catalogue.Name_Expected =>
               "_: u32 = 1"
               & LF,
            when Catalogue.Type_Expected =>
               "empty: type = ()"
               & LF,
            when Catalogue.Expression_Expected =>
               "",
            when Catalogue.Token_Expected =>
               "extern(c) bad: (...) -> none"
               & LF,
            when Catalogue.Unclosed_Construct =>
               "f: () -> (r: i32) ="
               & LF
               & "    r = 1"
               & LF,
            when Catalogue.Assignment_In_Expression =>
               "f: () -> (r: i32) ="
               & LF
               & "    mut n: i32 = 0"
               & LF
               & "    r = (n = 1)"
               & LF
               & "end f"
               & LF,
            when Catalogue.Comparison_Chained =>
               "f: (a: i32, b: i32, c: i32) -> (r: bool) = a < b < c end"
               & LF,
            when Catalogue.Return_Carries_Value =>
               "f: () -> (r: i32) ="
               & LF
               & "    return 1"
               & LF
               & "end f"
               & LF,
            when Catalogue.Public_On_Statement =>
               "f: () -> none ="
               & LF
               & "    public n: u32 = 1"
               & LF
               & "end f"
               & LF,
            when Catalogue.End_Name_Mismatch =>
               "f: () -> none ="
               & LF
               & "end g"
               & LF,
            when Catalogue.Stray_Token =>
               "begin = 10"
               & LF,
            when Catalogue.Nesting_Too_Deep =>
               "",
            when Catalogue.Positional_After_Named =>
               "take: (first: i32, second: i32, third: i32) -> none ="
               & LF
               & "end take"
               & LF
               & LF
               & "bad: () -> none ="
               & LF
               & "    take(first: 1, 2, 3)"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Duplicate_Declaration =>
               "first: u32 = 1"
               & LF
               & "first: u32 = 2"
               & LF,
            when Catalogue.Unresolved_Name =>
               "state := nowhere(value: 1)"
               & LF,
            when Catalogue.Inaccessible_Name =>
               "",
            when Catalogue.Reserved_Tool_Name =>
               "",
            when Catalogue.Literal_Out_Of_Range =>
               "over: u8 = 300"
               & LF,
            when Catalogue.Type_Mismatch =>
               "v: i32 = 1"
               & LF
               & "n: v = 2"
               & LF,
            when Catalogue.Not_Definitely_Assigned =>
               "make: () -> (result: [2]i32) ="
               & LF
               & "end make"
               & LF,
            when Catalogue.Immutable_Target =>
               "f: (x: u32) -> none ="
               & LF
               & "    x = 1"
               & LF
               & "end f"
               & LF,
            when Catalogue.Unsupported_Use =>
               "wide: u128 = 1"
               & LF,
            when Catalogue.Not_Known_At_Compile_Time =>
               "a: i32 = b + 1"
               & LF
               & "b: i32 = a + 1"
               & LF,
            when Catalogue.Impossible_Operand =>
               "quotient: u32 = 7 / 0"
               & LF,
            when Catalogue.Compile_Time_Assertion_Failed =>
               "",
            when Catalogue.Cyclic_Type_Alias =>
               "a: type = b"
               & LF
               & "b: type = a"
               & LF,
            when Catalogue.Unresolved_Field =>
               "point: type = struct"
               & LF
               & "    x: i32"
               & LF
               & "end point"
               & LF
               & LF
               & "f: () -> none ="
               & LF
               & "    local: point = (z: 1, of zeroed)"
               & LF
               & "end f"
               & LF,
            when Catalogue.Field_Named_Twice =>
               "bad: type (item: type) = struct"
               & LF
               & "    value: u8"
               & LF
               & "    value: item"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Field_Not_Given =>
               "point: type = struct"
               & LF
               & "    x: i32"
               & LF
               & "    y: i32"
               & LF
               & "end point"
               & LF
               & LF
               & "f: () -> none ="
               & LF
               & "    local: point = (x: 1)"
               & LF
               & "end f"
               & LF,
            when Catalogue.Variant_Case_Named_Twice =>
               "",
            when Catalogue.Variant_Case_Not_Matched =>
               "north, south: atom"
               & LF
               & "compass: type = north | south"
               & LF
               & LF
               & "f: (direction: compass) -> (value: i32) ="
               & LF
               & "    value = match direction"
               & LF
               & "        north: 1"
               & LF
               & "    end match"
               & LF
               & "end f"
               & LF,
            when Catalogue.Recursive_Nominal_Value =>
               "node: type = struct"
               & LF
               & "    next: node"
               & LF
               & "end node"
               & LF,
            when Catalogue.Reference_Escapes =>
               "bad: () -> (pointer: ptr u32) ="
               & LF
               & "    value: u32 = 1"
               & LF
               & "    pointer = addr value"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Borrowed_Place =>
               "mutate: (inout source: []mut u32) -> none ="
               & LF
               & "end mutate"
               & LF
               & "bad: (source: []mut u32) -> (result: u32) ="
               & LF
               & "    mut local := source"
               & LF
               & "    view := addr local[0]"
               & LF
               & "    mutate(local)"
               & LF
               & "    result = view.val"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Return_Sources_Disagree =>
               "bad: (source: ptr u32) -> (pointer: ptr u32) ="
               & LF
               & "    pointer = source"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Conformance_Collision =>
               "ordered: type = concept (t: type)"
               & LF
               & "end ordered"
               & LF
               & LF
               & "i32 is ordered ()"
               & LF
               & "i32 is ordered ()"
               & LF,
            when Catalogue.Unsatisfied_Constraint =>
               "cell: type (t: type is zeroable) = struct"
               & LF
               & "    value: t"
               & LF
               & "end cell"
               & LF
               & LF
               & "bad: type = cell(ptr i32)"
               & LF,
            when Catalogue.Compiler_Conformance_Reserved =>
               "i32 is zeroable ()"
               & LF,
            when Catalogue.Malformed_Text_Literal =>
               "name: []u8 = ""bad\q"""
               & LF,
            when Catalogue.Malformed_Float_Literal =>
               "ratio: f64 = 1e10"
               & LF,
            when Catalogue.Malformed_Character_Literal =>
               "bad: u32 = ''"
               & LF,
            when Catalogue.Malformed_Raw_Literal =>
               "bad: []u8 = """""""
               & LF
               & "    enough"
               & LF
               & "  short"
               & LF
               & "    """""""
               & LF,
            when Catalogue.Size_Limit_Exceeded =>
               "",
            when Catalogue.Mutable_Never_Written =>
               "count_up: () -> (total: u32) ="
               & LF
               & "    mut step: u32 = 2"
               & LF
               & "    total = step + 1"
               & LF
               & "end count_up"
               & LF,
            when Catalogue.No_Toolchain =>
               "",
            when Catalogue.Toolchain_Failed =>
               "",
            when Catalogue.Entry_Point_Missing =>
               "",
            when Catalogue.Argument_Not_In_A_Register =>
               "",
            when Catalogue.Frame_Not_Addressable =>
               "",
            when Catalogue.Image_Materialization_Limit =>
               "",
            when Catalogue.Panic_Contract_Invalid =>
               "");

end Landin.Diagnostics.Explanations;
