--  Generated by check.py from docs/diagnostics.md.  Do not edit;
--  regenerate with python3 check.py --catalogue.

package body Landin.Diagnostics.Explanations is

   LF : constant Character := Character'Val (10);

   function Explanation (Of_Code : Catalogue.Code_Name) return String
     is (case Of_Code is
            when Catalogue.No_Frontend =>
               "Retired. A source was read and no frontend was wired to "
               & "the driver. The frontend has been wired since the first "
               & "executable slice, so nothing raises this and the number "
               & "is kept so no other rule can take it.",
            when Catalogue.Unknown_Option =>
               "The command line asked for something the driver does not"
               & " define: an unknown option, an option without its value "
               & "or repeated where it may not be, or a combination the dr"
               & "iver refuses, such as `--emit` with no source, an output"
               & " that would overwrite a source or another output, or `re"
               & "fine explain` with a code no catalogue row holds. `refin"
               & "e --help` lists the options. The status is 2, which says"
               & " the request and not a program was wrong."
               & LF
               & LF
               & "Give `--target=` only once. Repeating it is a misuse eve"
               & "n when both names are the same; the driver does not choo"
               & "se between target selections."
               & LF
               & LF
               & "`--toolchain=NAME` and `--linker=NAME` require `--emit=e"
               & "xe`: checking and assembly emission do not run a linker."
               & " They are also incompatible with `--help` and `--identif"
               & "y`, which do not compile. Each selection must have a non"
               & "empty value and may be given only once.",
            when Catalogue.Unreadable_Source =>
               "A source named on the command line is missing or cannot "
               & "be read. Check the path and its permissions.",
            when Catalogue.Unknown_Target =>
               "`--target=` names no target the compiler describes, or n"
               & "one was named and this compiler's own host is not a desc"
               & "ribed target, so a build has nothing to compile for unti"
               & "l one is named. `refine --identify` lists the described "
               & "targets.",
            when Catalogue.Unwritable_Output =>
               "An output file cannot be written, or `refine fmt` cannot"
               & " safely replace its input. For emitted output, check tha"
               & "t the destination directory exists and is writable, or c"
               & "hoose another path with `-o`."
               & LF
               & LF
               & "Formatting needs a writable ordinary file owned by the c"
               & "aller and write permission in its directory. Hard links,"
               & " ACLs, extended attributes and an inability to establish"
               & " their absence cause refusal. On Linux, ordinary users m"
               & "ay be unable to inspect privileged attributes even on ap"
               & "parently plain files. Editor formatting can return edits"
               & " without replacing the file. A refused formatter replace"
               & "ment leaves the original bytes intact; see [formatter fi"
               & "le handling](format.md) for the full contract.",
            when Catalogue.Module_Not_Found =>
               "No import root holds the module an import names [1420]. "
               & "Roots are searched in the order `--root=` gives them, an"
               & "d a path's segments are directories under a root, spelle"
               & "d exactly. When a directory near the missing segment is "
               & "there, the diagnostic offers it as a likely fix.",
            when Catalogue.Module_Directory_Invalid =>
               "With `--root=`, the entry module must be a readable dire"
               & "ctory [1410]. Pass the directory, not a file inside it. "
               & "This code also reports an import root or intermediate di"
               & "rectory that cannot be listed while searching in root or"
               & "der [1420]. Check the named path and its permissions; a "
               & "genuinely absent module is reported by L0006.",
            when Catalogue.Not_Formatted =>
               "`refine fmt --check` found a source that is not in the l"
               & "ayout D252 decides and `docs/format.md` shows. The diagn"
               & "ostic points at the first line that would change. Nothin"
               & "g is wrong with the program: run `refine fmt` on the fil"
               & "e to put it in the layout, which changes its space and n"
               & "othing else.",
            when Catalogue.Unknown_Level =>
               "`--level=`, or the language server's `level` option, nam"
               & "es no CPU feature level of the selected target's family "
               & "(D255). A level belongs to one family, so `armv8.1-a` is"
               & " refused with `--target=linux-x86-64`, and synthetic-32 "
               & "has no level to select. `refine --identify` lists each t"
               & "arget's levels.",
            when Catalogue.Construct_Not_Enabled =>
               "The program uses a construct the tour describes and the "
               & "kernel does not enable yet [1830]. The two notes name th"
               & "e tour paragraph and whether the form is a recorded boun"
               & "dary, withdrawn with a replacement, or transferred to la"
               & "ter work. Write the program without it, or with what the"
               & " note says replaces it.",
            when Catalogue.Malformed_Integer =>
               "An integer literal has a digit its base does not have, o"
               & "r runs straight into a name [1770]. `0x` takes hexadecim"
               & "al digits, `0b` binary and `0o` octal, and a literal nee"
               & "ds a separator before a following name.",
            when Catalogue.Unknown_Bytes =>
               "A run of bytes no lexical rule spells [1750]. A name is "
               & "lower case [1760], and a byte outside the source alphabe"
               & "t belongs in a text literal.",
            when Catalogue.Unterminated_Comment =>
               "A block comment that is never closed [1780]. Every opene"
               & "r needs its closer; the second label shows where the com"
               & "ment began.",
            when Catalogue.Unterminated_Literal =>
               "An ordinary quoted text or character literal must close "
               & "before its line ends [0250] [0260]. A raw text literal m"
               & "ay span lines [0280]. Its maximal opening quote run sets"
               & " the delimiter width; only a later run of at least that "
               & "many quotes closes it. A shorter run remains content. Cl"
               & "ose the ordinary literal on its line, or add enough clos"
               & "ing quotes to the raw literal.",
            when Catalogue.Name_Expected =>
               "A name belongs here and something else stands there [176"
               & "0]. A keyword is never a name, including a control word "
               & "in any position (D225), and `_` alone is the discard. Ch"
               & "oose another name, such as `begin_value` for `begin`.",
            when Catalogue.Type_Expected =>
               "A type position holds nothing the kernel enables as a ty"
               & "pe [1790].",
            when Catalogue.Expression_Expected =>
               "An expression was required and none begins here [1820]: "
               & "an operator with no operand, or a separator where a valu"
               & "e belongs.",
            when Catalogue.Token_Expected =>
               "A token the grammar requires is absent [1810]. The secon"
               & "d label points at the construct that required it. When a"
               & " name near the required keyword stands in its place, suc"
               & "h as `thne` for `then`, the diagnostic offers the keywor"
               & "d as a likely fix.",
            when Catalogue.Unclosed_Construct =>
               "A construct opened and its `end` never arrived [1800]. T"
               & "he second label shows where it opened; close it there.",
            when Catalogue.Assignment_In_Expression =>
               "Assignment is a statement and never an expression [0390]"
               & ". `==` compares. When the assignment is an `=`, the diag"
               & "nostic offers `==` as a likely fix.",
            when Catalogue.Comparison_Chained =>
               "A comparison takes at most one operator [1820]: `a < b <"
               & " c` compares a `bool` with `c`. Write `a < b and b < c`.",
            when Catalogue.Return_Carries_Value =>
               "`return` carries no value [1810]. Assign the named retur"
               & "n, then `return`.",
            when Catalogue.Public_On_Statement =>
               "`public` belongs on a module declaration and never on a "
               & "statement [1740].",
            when Catalogue.End_Name_Mismatch =>
               "The name after `end` must be the name of what it closes "
               & "[1800], or be absent where the construct allows that. Th"
               & "e diagnostic offers the declared name as an exact fix.",
            when Catalogue.Stray_Token =>
               "A run of tokens begins no declaration or statement [1740"
               & "]. Often a keyword used as a name (D225), or a line left"
               & " from an edit.",
            when Catalogue.Nesting_Too_Deep =>
               "An implementation limit, not a rule of the language: a c"
               & "onstruct nests more deeply than the parser holds. Split "
               & "the expression or the block into named parts.",
            when Catalogue.Positional_After_Named =>
               "A positional argument follows a named one [0980]. Every "
               & "positional argument comes first.",
            when Catalogue.Duplicate_Declaration =>
               "One scope gives one name to one thing [1850]. Two declar"
               & "ations of one name in one scope, or two imports with one"
               & " final segment, are refused, and the second label shows "
               & "the first. An inner scope may shadow an outer name; that"
               & " is not this.",
            when Catalogue.Unresolved_Name =>
               "A name that is declared in no scope this use reaches [18"
               & "60]. There is no implicit declaration, so it is a misspe"
               & "lling or a name used outside its scope. When a declared "
               & "name the position could mean is near it, the diagnostic "
               & "offers that name as a likely fix: a local or parameter, "
               & "a type, a public member of an imported module, never a n"
               & "ame out of scope or inaccessible.",
            when Catalogue.Inaccessible_Name =>
               "A declaration of another module is used and it is not `p"
               & "ublic` [1410]. The second label shows the declaration. M"
               & "ake it `public` in its module, or use something that mod"
               & "ule does export.",
            when Catalogue.Reserved_Tool_Name =>
               "A tool namespace, `compiler`, `assembler` or `linker`, i"
               & "s bound or used in a way it does not allow [1560] (D202)"
               & ". Those three are in scope without an import and cannot "
               & "be imported, rebound or given a member they do not have.",
            when Catalogue.Literal_Out_Of_Range =>
               "A value known at compile time does not fit the type its "
               & "context gives it [1880], or the target cannot hold it. W"
               & "rite a smaller value or give the context a wider type.",
            when Catalogue.Register_Reserved_Bits =>
               "A register image known at compile time violates its rese"
               & "rved-bit write policy [0740] (D228). Supply zero in ever"
               & "y unnamed bit for `write_zero`, or one in every unnamed "
               & "bit for `write_one`. A whole-image write cannot repair t"
               & "hose bits by reading the device. The image may fit its c"
               & "arrier type; L0300 instead reports a value that its type"
               & " or target cannot hold.",
            when Catalogue.Type_Mismatch =>
               "A value's type is not the one its context or operation r"
               & "equires [1890], and no conversion is implied [0310]. Thi"
               & "s includes a literal that its context cannot type [1880]"
               & " [0210] [0260], an expression with no value type where o"
               & "ne is needed, a type-qualified name its type does not ha"
               & "ve [0240], an operation such as indexing, slicing, selec"
               & "tion or a call applied to a value whose type has none [1"
               & "820], an operator given an operand class it does not adm"
               & "it, a struct of another nominal type [0710], an array of"
               & " another length or element type, a function of another s"
               & "ignature [1000], or a reference of another permission [0"
               & "440]. The second label shows where the requirement was s"
               & "tated. Change the value, or convert it explicitly where "
               & "a conversion exists.",
            when Catalogue.Not_Definitely_Assigned =>
               "Required storage is not definitely assigned at a read or"
               & " an exit [1910]. A read needs the place assigned on ever"
               & "y path that reaches it. Reading a whole aggregate also r"
               & "eads its parts; a computed local-array index requires th"
               & "e whole array assigned (D19-D22). Assign the needed plac"
               & "e before the read on every arriving path, or give it a v"
               & "alue where it is declared."
               & LF
               & LF
               & "After `sink`, the consumed place is dead until assigned "
               & "again [0910]. Assign it or its enclosing aggregate befor"
               & "e a later read. A consumed part of an `inout` parameter "
               & "must also be restored on every exit, including `fail` an"
               & "d `try` failure propagation: the caller can observe that"
               & " storage after a recovered failure. Assign it on each ex"
               & "it path, either before the exit or in an applicable `def"
               & "er` or `undo` cleanup, which runs before this check. A n"
               & "amed result must be fully assigned on successful return "
               & "[0930], including any part consumed by `sink`; failure e"
               & "xits do not require the named result.",
            when Catalogue.Immutable_Target =>
               "A place that may not be written [1900]: an immutable bin"
               & "ding, an `in` parameter, an atom, a function, or storage"
               & " reached through a read-only reference. When the place i"
               & "s a local or module binding of one name, the diagnostic "
               & "offers `mut` on its declaration as a likely fix.",
            when Catalogue.Unsupported_Use =>
               "A known form used where the language does not permit it "
               & "[1830], found once the checker knows what the form means"
               & ". The report names the specific rule; its two notes give"
               & " the tour paragraph and the form's standing."
               & LF
               & LF
               & "For a variant [0680]-[0690] (D75/D76/D241), its part bel"
               & "ongs to the enclosing struct and has no standalone value"
               & ". Match the part to inspect its case, or copy the whole "
               & "struct. To change the part, write one of its cases to a "
               & "directly selected part of a mutable struct, or supply th"
               & "at case while constructing the struct. A case cannot ini"
               & "tialize an unrelated binding as a standalone value: its "
               & "destination must supply its variant part. A case without"
               & " payload may be bare; write a payload case with labelled"
               & " fields.",
            when Catalogue.Not_Known_At_Compile_Time =>
               "A required static value or initial image cannot be estab"
               & "lished before the program runs [1940] (D136, D202). A mo"
               & "dule value, array bound or fixed configuration expressio"
               & "n can depend on a runtime value or call, contain an unkn"
               & "own fixed name or form, or depend on itself. Change such"
               & " an expression to one the closed fold can evaluate. A mo"
               & "dule function binding without an initializer has no impl"
               & "icit zero function address; give it an initial function "
               & "address, such as a declared function or another module f"
               & "unction value whose image is known.",
            when Catalogue.Impossible_Operand =>
               "An operand the operation cannot take, where the compiler"
               & " knows it [1950]: a divisor of zero, a shift by a negati"
               & "ve amount, an index outside a fixed array, or a range su"
               & "btype whose bounds are reversed.",
            when Catalogue.Compile_Time_Assertion_Failed =>
               "A compile-time assertion is false [1510].",
            when Catalogue.Cyclic_Type_Alias =>
               "A chain of type aliases that never reaches a type [1795]"
               & ".",
            when Catalogue.Unresolved_Field =>
               "A field a struct, a variant case or a result was not dec"
               & "lared with [0750] [0990]. When a declared field is near "
               & "the written name, the diagnostic offers it as a likely f"
               & "ix.",
            when Catalogue.Field_Named_Twice =>
               "A struct declaration [0670] or literal [0710] repeats a "
               & "field name, a variant case declaration [0680] (D74) repe"
               & "ats a payload field name, or a case construction (D76) s"
               & "upplies the same payload field twice. Remove or rename a"
               & " repeated declaration field; in a literal or constructio"
               & "n, supply each field once."
               & LF
               & LF
               & "For a case declared as `pair: (first: u8, second: bool)`"
               & ", the construction `pair(first: 1, first: 2, second: tru"
               & "e)` repeats `first`.",
            when Catalogue.Field_Not_Given =>
               "A struct literal [0710] or variant case construction (D7"
               & "6) omits a field without a trailing `of zeroed`. Supply "
               & "the missing field, or use `of zeroed` when every omitted"
               & " field has a zero image."
               & LF
               & LF
               & "For a case declared as `pair: (first: u8, second: bool)`"
               & ", the construction `pair(first: 1)` omits `second`.",
            when Catalogue.Variant_Case_Named_Twice =>
               "A match names one variant case twice [1210].",
            when Catalogue.Variant_Case_Not_Matched =>
               "A match leaves a case unnamed [1210]. For a variant part"
               & ", add an arm naming each missing case. For an atom set o"
               & "r pointer union, name the missing cases or put a `_:` ar"
               & "m last to cover them.",
            when Catalogue.Recursive_Nominal_Value =>
               "A struct holds itself by value, so its layout could neve"
               & "r be finite (D137). Hold it through a pointer.",
            when Catalogue.Reference_Escapes =>
               "Retaining a reference requires both storage that remains"
               & " live and permission from its origin [0770] [0780]. A re"
               & "ference into this function's frame cannot be returned, p"
               & "assed to a retaining (`escaping`) parameter, or stored o"
               & "utside the frame. Move the referenced value to storage t"
               & "hat actually outlives the retention, or stop retaining t"
               & "he reference. Declaring a parameter `escaping` does not "
               & "extend the lifetime of frame storage."
               & LF
               & LF
               & "Parameters are non-escaping by default. A reference deri"
               & "ved from one cannot be passed to a retaining (`escaping`"
               & ") call or stored in another origin, even if the referenc"
               & "ed storage will remain live. If that retention is intend"
               & "ed, declare the source parameter `escaping` and make its"
               & " callers satisfy that contract. Otherwise, keep the use "
               & "non-retaining or update storage within the same origin. "
               & "Keeping the storage alive longer alone does not grant re"
               & "tention permission.",
            when Catalogue.Borrowed_Place =>
               "A place is changed while a view derived from it is still"
               & " in use [0800] [0830]. Finish with the view first, or ta"
               & "ke it again after the change.",
            when Catalogue.Return_Sources_Disagree =>
               "A returned reference must derive from exactly the parame"
               & "ters its `from` names [0790]. Name the source, or return"
               & " something derived from it.",
            when Catalogue.Conformance_Collision =>
               "Two conformances of one type to one concept [1280]. Ther"
               & "e is one register for the whole program; remove one, or "
               & "give one type `distinct` identity.",
            when Catalogue.Unsatisfied_Constraint =>
               "A type given for a formal lacks a conformance the formal"
               & " requires [1290].",
            when Catalogue.Compiler_Conformance_Reserved =>
               "The compiler owns `zeroable` and its conformances; a pro"
               & "gram declares neither.",
            when Catalogue.Malformed_Text_Literal =>
               "A text literal holds an escape the language does not def"
               & "ine, or bytes that are not UTF-8 [0270] [1750].",
            when Catalogue.Malformed_Float_Literal =>
               "A float literal needs its fraction, and an exponent wher"
               & "e its form requires one [0210] [0220] [0230].",
            when Catalogue.Malformed_Character_Literal =>
               "A character literal holds exactly one Unicode scalar val"
               & "ue [0250] [0270].",
            when Catalogue.Malformed_Raw_Literal =>
               "A raw literal's content is UTF-8, and each line that is "
               & "not blank starts with the closing delimiter's indentatio"
               & "n [0280] [1750].",
            when Catalogue.Size_Limit_Exceeded =>
               "An implementation limit, not a rule of the language: a r"
               & "outine has too many declarations, or a struct body or va"
               & "riant case has too many fields (D247). Split the routine"
               & " or reduce the fields in the body or case.",
            when Catalogue.Invalid_Option_Declaration =>
               "An `option` declaration breaks [1530]/D202: it is inside"
               & " a fixed arm, reuses a compiler-owned configuration atom"
               & " name, or declares a type other than `bool` or an enable"
               & "d integer scalar. Move the option outside every fixed ar"
               & "m, choose an available name, or change its type, respect"
               & "ively. A fixed default value does not make any of those "
               & "declarations valid.",
            when Catalogue.Invalid_Tool_Directive =>
               "A tool directive breaks [1510]/[1590]/D202 when it has o"
               & "ther than one positional argument, or when `linker.libra"
               & "ry` has an argument that is not a quoted text literal wi"
               & "th a portable static library name. Give `compiler.assert"
               & "` one fixed bool expression. Give `linker.library` one q"
               & "uoted text literal containing a portable static library "
               & "name; its argument must have the required form and name "
               & "characters.",
            when Catalogue.Mutable_Never_Written =>
               "A warning, and the program is accepted: a local binding "
               & "is declared `mut` and nothing writes it, steps it, passe"
               & "s it `inout` or takes a mutable view of it. Without `mut"
               & "` it means the same, so the diagnostic offers removing t"
               & "he word as an exact fix. The language permits the `mut`;"
               & " the warning is the compiler's judgement and not a rule "
               & "(D251). A shared declaration is warned about only when n"
               & "one of its names is written, and a module binding never "
               & "is, since a linked routine or a debugger may write it.",
            when Catalogue.Call_Argument_Match =>
               "A call's arguments do not match what the callee takes [1"
               & "920]. A runtime argument is missing, extra or given twic"
               & "e; a named argument names no parameter [0980]; a `caller"
               & "` parameter is filled other than by forwarding another o"
               & "ne (D186); a static argument is given where the callee h"
               & "as no static formal [1300], or a static formal is used a"
               & "s a runtime value [1290]; a generic call gives a differe"
               & "nt number of arguments than its template (D138); or a co"
               & "nversion is not given exactly one value [0700]. Supply e"
               & "very parameter exactly once, in the callee's declared fo"
               & "rm. The second label points to the signature or paramete"
               & "r. When a named argument names no parameter, the diagnos"
               & "tic offers the parameter label near it as a likely fix.",
            when Catalogue.Zero_Image_Unavailable =>
               "`zeroed` or an implicit initializer has no complete zero"
               & " image to supply [0540]. `zeroed`, an implicit module in"
               & "itializer, and a module atom binding without an initiali"
               & "zer [0630] each need the destination type's all-bits-zer"
               & "o image. A pointer, function address, atom set without a"
               & " zero identity, or aggregate containing one has no such "
               & "image, and `zeroed` nested in an expression or used as a"
               & "n operand has no destination to take its type from. Give"
               & " an explicit initializer that constructs a valid value, "
               & "use a type with a zero image, or write `zeroed` as the w"
               & "hole value of a typed destination.",
            when Catalogue.Error_Contract_Violated =>
               "A failure does not follow the declared error contract [0"
               & "940] [0960] [1030]. `fail` carries exactly one atom of t"
               & "he function's declared error set. A call to a failing fu"
               & "nction handles the outcome with `else` or propagates it "
               & "with `try`, and neither form applies to a call that cann"
               & "ot fail. A public or first-class signature writes a conc"
               & "rete error set instead of `! ...`. Add the atom to the e"
               & "rror set, handle or propagate the call, or remove the ha"
               & "ndling from an infallible call. The implicit provider ca"
               & "lls in `try for` also propagate their declared errors: t"
               & "he enclosing routine must declare or infer those atoms, "
               & "and its caller may recover them through ordinary call `e"
               & "lse`.",
            when Catalogue.Assembly_Block_Contract =>
               "An assembly block, operand or template breaks [1630]'s b"
               & "lock contract or [1990]'s register rules. Only `assemble"
               & "r.block` accepts operands. Each operand is one integer r"
               & "egister, named by its target-wide name or chosen with `g"
               & "eneral`, and never a stack, frame, link or reserved regi"
               & "ster. Every `{name}` in the template names one operand. "
               & "A naked body is exactly one block. Change the operand, r"
               & "egister or template as the note says, or move the operan"
               & "ds into an assembly block.",
            when Catalogue.Result_Use =>
               "A call's result is used in a way its signature does not "
               & "allow. A result that is handed back must be used or disc"
               & "arded with `_ =` [1020], and a call that returns none ha"
               & "s no value to use, infer from, or discard [1920] [1930]."
               & " Destructuring binds the names of a multiple result, eac"
               & "h at most once [0990]. Discard the result explicitly, us"
               & "e a call that returns one, or bind the result names the "
               & "signature declares.",
            when Catalogue.Control_Value =>
               "A `break` must carry a value exactly when its target nee"
               & "ds one [1180] [1190]; every value-producing fallthrough "
               & "must supply one (D124). Every `break` out of a loop used"
               & " as an expression carries `with`. A finite expression lo"
               & "op leaves through `break with` when it completes. Every "
               & "fallthrough path of a value-producing `if` or block prod"
               & "uces a value; an early return need not. A labelled bare "
               & "block and a statement loop take no value. Add `with` and"
               & " a value to a break from an expression loop. Remove `wit"
               & "h` from a break to a statement loop or labelled bare blo"
               & "ck. Supply a value on each fallthrough path, or use the "
               & "construct as a statement.",
            when Catalogue.Match_Arm_Form =>
               "A `match` arm does not fit its subject [1210]. A subject"
               & " is an atom set, a variant part or a pointer union. Each"
               & " arm names a case or atom of that subject at most once ("
               & "D77) [0640] [0480]. A `ptr` arm matches only a pointer u"
               & "nion and binds one read-only pointer [1220]. Atom arms b"
               & "ind no payload [0630]. A wildcard arm comes last and bin"
               & "ds nothing. Variant payload names are positional and com"
               & "plete (D78). Rewrite the arm in the form its subject adm"
               & "its, or compare numbers with `if` and `elsif`.",
            when Catalogue.Aggregate_Form =>
               "A struct, variant or array value is built or used outsid"
               & "e its admitted form [0700] [0720]. A construction applie"
               & "s a struct type to labelled field values, and its fill s"
               & "upplies one value for the omitted fields. A variant case"
               & " is written where its part is the destination [0690] (D7"
               & "6). A whole struct or array is copied, passed, returned "
               & "or discarded whole [0670] [0520]. A repetition prefix le"
               & "aves a suffix to fill (D36). Write the value in the form"
               & " the note names, at a position that takes it.",
            when Catalogue.Pointer_Union_Use =>
               "A union of atoms and one pointer is used as a pointer be"
               & "fore it is matched [0480]. Match it first: the `ptr` arm"
               & " binds the pointer, and each atom arm names the empty ca"
               & "se. A pointer case is constructed only from a pointer, a"
               & "nd a known zero address is reserved for the union's empt"
               & "y atom [0460]. Match the union, or construct it from an "
               & "atom or a pointer.",
            when Catalogue.Packed_Image =>
               "A packed image or its layout is used outside [0730]'s ru"
               & "les. Packed fields have explicit, disjoint bit positions"
               & " within one unsigned image, and an encoded union has dis"
               & "tinct atoms and encodings. A packed width such as `u2` i"
               & "s a field representation, not an ordinary value type. A "
               & "packed field has no address of its own, cannot be passed"
               & " `inout`, and cannot be sliced; the image is not a scala"
               & "r operand (D228). Correct the layout, or work through th"
               & "e containing image and its fields.",
            when Catalogue.Place_Required =>
               "An operation that needs a distinct addressable place was"
               & " given something else. `addr` takes a storage place [043"
               & "0], not a computed value such as a utf8 index result [06"
               & "10]. Two `inout` arguments cannot be one place [0900], a"
               & "nd a `sink` argument is a place rooted in a binding [091"
               & "0]. Store the value in a binding first, or pass two diff"
               & "erent places.",
            when Catalogue.Type_Declaration_Form =>
               "A type position or type declaration is not well formed. "
               & "A type position names a scalar type or a `type` declarat"
               & "ion, and a type name is not a runtime value [1795]. A ty"
               & "pe alias is applied with its exact positional arguments "
               & "[1350]. A union holds atoms and at most one pointer type"
               & " [0640]; a range subtype restricts an integer type [0660"
               & "]; a fixed-array bound is an integer count (D136). Corre"
               & "ct the declaration or name a type.",
            when Catalogue.Signature_Form =>
               "A written signature is not well formed. A function type "
               & "gives each parameter a distinct label [0980] and each re"
               & "sult a distinct name [0990]. A `from` clause names borro"
               & "wed runtime parameters, once each, on a result that hold"
               & "s a reference [0790]. A `caller` parameter has the exact"
               & " source-position struct (D192). Rename or remove the dup"
               & "licate, or correct the clause.",
            when Catalogue.Generic_Deduction =>
               "A generic call cannot deduce and instantiate one concret"
               & "e routine (D138). Deduction matches each runtime argumen"
               & "t against its written parameter pattern; it never uses t"
               & "he return context, conversions or constraints, and repea"
               & "ted deductions must agree, and the deduced actuals must "
               & "give a concrete, enabled signature whose fixed values fi"
               & "t their formals. A generic template has no function valu"
               & "e until it is called. Recursion that keeps changing the "
               & "actual tuple never ends, and a circular error-set depend"
               & "ency cannot be resolved (D215). Give the type argument e"
               & "xplicitly, pass arguments that agree, or call a concrete"
               & " routine.",
            when Catalogue.Conformance_Form =>
               "A concept or conformance declaration is not well formed "
               & "[1230]-[1270]. A concept is parameterized by types and n"
               & "ames each entry once. Composition is finite, and a stati"
               & "c entry name is unique across the concept closure (D221)"
               & ". Every entry fixes one concrete error set. A conformanc"
               & "e names a declared concept, supplies each input and entr"
               & "y once by label, and provides each entry with a function"
               & " of exactly the required signature. A parameterized conf"
               & "ormance applies its complete binder. Correct the declara"
               & "tion against the concept it names.",
            when Catalogue.Erased_Contract =>
               "An `any` value or its dispatch is used outside the erase"
               & "d contract [1370] [1380] [1390] (D145-D147). `any C` nam"
               & "es a concept with runtime entries, each dispatch name un"
               & "ique across its closure, and erases a pointer, never a v"
               & "alue; every entry takes the erased `self` pointer first;"
               & " an entry is called directly and is not a bound value; a"
               & " concrete pointer selects exactly one conformance, and t"
               & "he closed program has a runtime table for it; and a modu"
               & "le `any` binding has no implicit null pair. Pass a point"
               & "er, write the `any C` context, or adjust the concept's e"
               & "ntries.",
            when Catalogue.Noreturn_Contract =>
               "A noreturn routine breaks its contract [0890]. A noretur"
               & "n signature is ordinary and infallible, and every reacha"
               & "ble path of its body diverges. Remove the error set, or "
               & "end every path in a call that does not return.",
            when Catalogue.Memory_Contract =>
               "A memory intrinsic is used outside its explicit contract"
               & " [1620] (D227). Each operation takes the operand types, "
               & "permissions and memory orderings its contract lists, the"
               & " target must support it, and an intrinsic cannot fail. U"
               & "se an ordering and operand the operation admits on this "
               & "target.",
            when Catalogue.Machine_Entry_Contract =>
               "An interrupt or naked routine is used outside its machin"
               & "e-entry contract [1570]. The machine convention is Corte"
               & "x-M0's and takes a nongeneric `() -> none` signature wit"
               & "hout errors. A naked body is one assembly block. A machi"
               & "ne entry is entered by its vector and is never called as"
               & " a routine. Correct the signature or body, or call an or"
               & "dinary routine instead.",
            when Catalogue.Foreign_Boundary =>
               "A C boundary declaration or call is something the C ABI "
               & "cannot carry [1580]. On a target with C ABI support, a C"
               & " signature is infallible and nongeneric, with at most on"
               & "e result. Each parameter and result part uses implicit o"
               & "r explicit `in`, without `caller` or a constraint. Its t"
               & "ype is a scalar, pointer (including a named optional poi"
               & "nter union), fixed infallible C callback, or `layout(c)`"
               & " struct; slices, `any`, atoms and by-value arrays are ex"
               & "cluded. A `layout(c)` struct has at least one field and "
               & "holds only C representations: scalars, pointers, fixed C"
               & " callbacks, nonempty fixed arrays or recursively `layout"
               & "(c)` structs, with no tagged variants. A variadic C decl"
               & "aration needs at least one fixed parameter and target su"
               & "pport; a variadic definition needs a generated adapter. "
               & "Variadic calls take positional scalar, pointer or fixed "
               & "C callback tail arguments, without labels or static argu"
               & "ments. Change `inout` or `sink` to `in`; pass a pointer "
               & "if C must write through a parameter. Remove `caller` and"
               & " constraints, specialize generics, represent errors thro"
               & "ugh an ordinary C result, and combine multiple results i"
               & "nto one C-representable result. Pass a pointer to a by-v"
               & "alue array or other unsupported aggregate, or change the"
               & " type or layout to one C represents.",
            when Catalogue.Linkage_Contract =>
               "A link symbol, helper import or firmware placement break"
               & "s [1610]'s or [1640]'s contract. A link symbol denotes o"
               & "ne compatible function and at most one definition. A com"
               & "piler-owned helper import keeps its source types, permis"
               & "sions and nullability. Only the entry module's hosted `m"
               & "ain` takes the `main` symbol. Cortex data symbols and se"
               & "ctions use the spellings, alignments and vectors [1640] "
               & "lists. Rename the symbol or correct the declaration.",
            when Catalogue.Traversal_Source =>
               "A `for` source is not something the loop can traverse [1"
               & "150]. A range traversal runs over integers, an array or "
               & "slice is walked by element, and a struct or `any C` sour"
               & "ce selects one exact iterable conformance with one `Cur`"
               & " and `Item` pair (D180). An ordinary pointer is not a `c"
               & "string` (D184). Traverse an integer range or a traversab"
               & "le value, or declare one iterable conformance. Each prov"
               & "ider takes a read-only, non-escaping `ptr T` to the reta"
               & "ined source, with the exact cursor, item, permission and"
               & " origin contract at [1320]; migrate a by-value source pa"
               & "rameter to that pointer contract."
               & LF
               & LF
               & "If the source supplies `fallible_iterable`, use `try for"
               & "` and declare or infer its provider errors in the enclos"
               & "ing routine. That conformance has one exact shared atom "
               & "error set across all four providers. Ordinary `for` only"
               & " selects infallible `iterable`; `try for` prefers `falli"
               & "ble_iterable` when both exist and may use ordinary `iter"
               & "able` when there is no fallible conformance.",
            when Catalogue.No_Toolchain =>
               "The requested output cannot be made with the selected ta"
               & "rget, settings or available toolchain [1550]. The diagno"
               & "stic and its note identify the cause: the target has no "
               & "backend, its source debug mode is unsupported, firmware "
               & "forbids `linker.library`, no toolchain is selected, or t"
               & "he named tool is unavailable. Choose a target with a bac"
               & "kend, change the debug or firmware configuration, or sel"
               & "ect or install a toolchain as the note directs. `--toolc"
               & "hain=` only helps when a toolchain is absent or unavaila"
               & "ble.",
            when Catalogue.Toolchain_Failed =>
               "Executable emission failed [1550]. The assembler or link"
               & "er may have refused the emitted code, or the requested o"
               & "utput could not be produced, verified, or restored. The "
               & "note describes the failure, names paths needed for recov"
               & "ery, and includes tool output when available.",
            when Catalogue.Entry_Point_Missing =>
               "`--emit=exe` needs an entry: a hosted `main` of the one "
               & "shape [1970] in the entry module, or the firmware routin"
               & "e `--firmware-entry=` names.",
            when Catalogue.Argument_Not_In_A_Register =>
               "Retired. An internal call could only pass arguments in r"
               & "egisters. The internal calling convention now places eve"
               & "ry argument after the sixth on the stack, so nothing rai"
               & "ses this.",
            when Catalogue.Frame_Not_Addressable =>
               "A verified frame is larger than x86-64's signed 32-bit d"
               & "isplacement reaches. Move the large local storage into a"
               & " module value or an allocation.",
            when Catalogue.Image_Materialization_Limit =>
               "Firmware static images exceed what the assembler is give"
               & "n to materialize [1640]. Make the static data smaller, o"
               & "r hold it in fewer, larger values.",
            when Catalogue.Panic_Contract_Invalid =>
               "The panic handler is invalid, or the program has more ch"
               & "eck sites than their identifier space holds [1670].",
            when Catalogue.Firmware_Frame_Exceeds_Stack =>
               "One routine's saved registers and local frame exceed the"
               & " selected 4 KiB firmware stack reservation [1990]. Move "
               & "large local storage elsewhere or make it smaller. This c"
               & "heck does not bound calls or interrupt nesting.");

   function Example (Of_Code : Catalogue.Code_Name) return String
     is (case Of_Code is
            when Catalogue.No_Frontend =>
               "",
            when Catalogue.Unknown_Option =>
               "",
            when Catalogue.Unreadable_Source =>
               "",
            when Catalogue.Unknown_Target =>
               "",
            when Catalogue.Unwritable_Output =>
               "",
            when Catalogue.Module_Not_Found =>
               "",
            when Catalogue.Module_Directory_Invalid =>
               "",
            when Catalogue.Not_Formatted =>
               "",
            when Catalogue.Unknown_Level =>
               "",
            when Catalogue.Construct_Not_Enabled =>
               "point: type = struct"
               & LF
               & "    x: i32"
               & LF
               & "end point"
               & LF
               & LF
               & "state: point = point(of zeroed)"
               & LF,
            when Catalogue.Malformed_Integer =>
               "mask: u64 = 1u64"
               & LF,
            when Catalogue.Unknown_Bytes =>
               "X: u32 = 1"
               & LF,
            when Catalogue.Unterminated_Comment =>
               "--( this one never closes"
               & LF
               & "f: () -> (r: i32) = 1 end"
               & LF,
            when Catalogue.Unterminated_Literal =>
               "value := ""never closed"
               & LF
               & "unclosed_raw: []u8 = """"""""never closed"""""""
               & LF,
            when Catalogue.Name_Expected =>
               "_: u32 = 1"
               & LF,
            when Catalogue.Type_Expected =>
               "empty: type = ()"
               & LF,
            when Catalogue.Expression_Expected =>
               "",
            when Catalogue.Token_Expected =>
               "extern(c) bad: (...) -> none"
               & LF,
            when Catalogue.Unclosed_Construct =>
               "f: () -> (r: i32) ="
               & LF
               & "    r = 1"
               & LF,
            when Catalogue.Assignment_In_Expression =>
               "f: () -> (r: i32) ="
               & LF
               & "    mut n: i32 = 0"
               & LF
               & "    r = (n = 1)"
               & LF
               & "end f"
               & LF,
            when Catalogue.Comparison_Chained =>
               "f: (a: i32, b: i32, c: i32) -> (r: bool) = a < b < c end"
               & LF,
            when Catalogue.Return_Carries_Value =>
               "f: () -> (r: i32) ="
               & LF
               & "    return 1"
               & LF
               & "end f"
               & LF,
            when Catalogue.Public_On_Statement =>
               "f: () -> none ="
               & LF
               & "    public n: u32 = 1"
               & LF
               & "end f"
               & LF,
            when Catalogue.End_Name_Mismatch =>
               "f: () -> none ="
               & LF
               & "end g"
               & LF,
            when Catalogue.Stray_Token =>
               "begin = 10"
               & LF,
            when Catalogue.Nesting_Too_Deep =>
               "",
            when Catalogue.Positional_After_Named =>
               "take: (first: i32, second: i32, third: i32) -> none ="
               & LF
               & "end take"
               & LF
               & LF
               & "bad: () -> none ="
               & LF
               & "    take(first: 1, 2, 3)"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Duplicate_Declaration =>
               "first: u32 = 1"
               & LF
               & "first: u32 = 2"
               & LF,
            when Catalogue.Unresolved_Name =>
               "state := nowhere(value: 1)"
               & LF,
            when Catalogue.Inaccessible_Name =>
               "",
            when Catalogue.Reserved_Tool_Name =>
               "",
            when Catalogue.Literal_Out_Of_Range =>
               "over: u8 = 300"
               & LF,
            when Catalogue.Register_Reserved_Bits =>
               "",
            when Catalogue.Type_Mismatch =>
               "flag: bool = true"
               & LF
               & "count: u8 = flag"
               & LF,
            when Catalogue.Not_Definitely_Assigned =>
               "unavailable: atom"
               & LF
               & "consume: (sink value: i32) -> none = end consume"
               & LF
               & "bad: (inout value: i32) -> none ! unavailable ="
               & LF
               & "    consume(value)"
               & LF
               & "    fail unavailable"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Immutable_Target =>
               "f: (x: u32) -> none ="
               & LF
               & "    x = 1"
               & LF
               & "end f"
               & LF,
            when Catalogue.Unsupported_Use =>
               "holder: type = struct"
               & LF
               & "    kind: variant"
               & LF
               & "        dot |"
               & LF
               & "        box: (w: u8)"
               & LF
               & "    end kind"
               & LF
               & "end holder"
               & LF
               & LF
               & "f: () -> none ="
               & LF
               & "    mut h: holder = zeroed"
               & LF
               & "    h.kind = dot      -- permitted: the part is the dest"
               & "ination"
               & LF
               & "    part := h.kind    -- L0304: the part has no standalo"
               & "ne value"
               & LF
               & "    alone := dot      -- L0304: the case needs its part "
               & "as destination"
               & LF
               & "end f"
               & LF,
            when Catalogue.Not_Known_At_Compile_Time =>
               "a: i32 = b + 1"
               & LF
               & "b: i32 = a + 1"
               & LF,
            when Catalogue.Impossible_Operand =>
               "quotient: u32 = 7 / 0"
               & LF,
            when Catalogue.Compile_Time_Assertion_Failed =>
               "",
            when Catalogue.Cyclic_Type_Alias =>
               "a: type = b"
               & LF
               & "b: type = a"
               & LF,
            when Catalogue.Unresolved_Field =>
               "point: type = struct"
               & LF
               & "    x: i32"
               & LF
               & "end point"
               & LF
               & LF
               & "f: () -> none ="
               & LF
               & "    local: point = (z: 1, of zeroed)"
               & LF
               & "end f"
               & LF,
            when Catalogue.Field_Named_Twice =>
               "bad: type (item: type) = struct"
               & LF
               & "    value: u8"
               & LF
               & "    value: item"
               & LF
               & "end bad"
               & LF
               & LF
               & "choice: type = struct"
               & LF
               & "    kind: variant"
               & LF
               & "        pair: (first: u8, first: bool)"
               & LF
               & "    end kind"
               & LF
               & "end choice"
               & LF,
            when Catalogue.Field_Not_Given =>
               "point: type = struct"
               & LF
               & "    x: i32"
               & LF
               & "    y: i32"
               & LF
               & "end point"
               & LF
               & LF
               & "f: () -> none ="
               & LF
               & "    local: point = (x: 1)"
               & LF
               & "end f"
               & LF,
            when Catalogue.Variant_Case_Named_Twice =>
               "",
            when Catalogue.Variant_Case_Not_Matched =>
               "north, south: atom"
               & LF
               & "compass: type = north | south"
               & LF
               & LF
               & "f: (direction: compass) -> (value: i32) ="
               & LF
               & "    value = match direction"
               & LF
               & "        north: 1"
               & LF
               & "    end match"
               & LF
               & "end f"
               & LF,
            when Catalogue.Recursive_Nominal_Value =>
               "node: type = struct"
               & LF
               & "    next: node"
               & LF
               & "end node"
               & LF,
            when Catalogue.Reference_Escapes =>
               "bad: () -> (pointer: ptr u32) ="
               & LF
               & "    value: u32 = 1"
               & LF
               & "    pointer = addr value"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Borrowed_Place =>
               "mutate: (inout source: []mut u32) -> none ="
               & LF
               & "end mutate"
               & LF
               & "bad: (source: []mut u32) -> (result: u32) ="
               & LF
               & "    mut local := source"
               & LF
               & "    view := addr local[0]"
               & LF
               & "    mutate(local)"
               & LF
               & "    result = view.val"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Return_Sources_Disagree =>
               "bad: (source: ptr u32) -> (pointer: ptr u32) ="
               & LF
               & "    pointer = source"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Conformance_Collision =>
               "ordered: type = concept (t: type)"
               & LF
               & "end ordered"
               & LF
               & LF
               & "i32 is ordered ()"
               & LF
               & "i32 is ordered ()"
               & LF,
            when Catalogue.Unsatisfied_Constraint =>
               "cell: type (t: type is zeroable) = struct"
               & LF
               & "    value: t"
               & LF
               & "end cell"
               & LF
               & LF
               & "bad: type = cell(ptr i32)"
               & LF,
            when Catalogue.Compiler_Conformance_Reserved =>
               "i32 is zeroable ()"
               & LF,
            when Catalogue.Malformed_Text_Literal =>
               "name: []u8 = ""bad\q"""
               & LF,
            when Catalogue.Malformed_Float_Literal =>
               "ratio: f64 = 1e10"
               & LF,
            when Catalogue.Malformed_Character_Literal =>
               "bad: u32 = ''"
               & LF,
            when Catalogue.Malformed_Raw_Literal =>
               "bad: []u8 = """""""
               & LF
               & "    enough"
               & LF
               & "  short"
               & LF
               & "    """""""
               & LF,
            when Catalogue.Size_Limit_Exceeded =>
               "",
            when Catalogue.Invalid_Option_Declaration =>
               "option debug: u32 = 1"
               & LF,
            when Catalogue.Invalid_Tool_Directive =>
               "linker.library(""-bad"")"
               & LF,
            when Catalogue.Mutable_Never_Written =>
               "count_up: () -> (total: u32) ="
               & LF
               & "    mut step: u32 = 2"
               & LF
               & "    total = step + 1"
               & LF
               & "end count_up"
               & LF,
            when Catalogue.Call_Argument_Match =>
               "add: (a: i32, b: i32) -> (r: i32) = a + b end add"
               & LF
               & "f: () -> (r: i32) = add(a: 1) end f"
               & LF,
            when Catalogue.Zero_Image_Unavailable =>
               "node: type = struct"
               & LF
               & "    value: i32"
               & LF
               & "end node"
               & LF
               & "bad: () -> none ="
               & LF
               & "    value: [3]ptr node = zeroed"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Error_Contract_Violated =>
               "missing, denied: atom"
               & LF
               & "f: () -> none ! missing ="
               & LF
               & "    fail denied"
               & LF
               & "end f"
               & LF,
            when Catalogue.Assembly_Block_Contract =>
               "record: (first: u32, second: u32) -> none = end record"
               & LF
               & "f: (value: u32) -> none ="
               & LF
               & "    record(1, in x: u32 at r0 = value)"
               & LF
               & "end f"
               & LF,
            when Catalogue.Result_Use =>
               "double: (x: i32) -> (r: i32) = r = x * 2 end double"
               & LF
               & "f: () -> none ="
               & LF
               & "    double(5)"
               & LF
               & "end f"
               & LF,
            when Catalogue.Control_Value =>
               "public main: () -> (code: i32) ="
               & LF
               & "    code = loop do"
               & LF
               & "        break when true"
               & LF
               & "        break with 1"
               & LF
               & "    end loop"
               & LF
               & "end main"
               & LF,
            when Catalogue.Match_Arm_Form =>
               "f: (n: u32) -> none ="
               & LF
               & "    match n"
               & LF
               & "        _: _ = 1"
               & LF
               & "    end match"
               & LF
               & "end f"
               & LF,
            when Catalogue.Aggregate_Form =>
               "record: type = struct"
               & LF
               & "    first: bool"
               & LF
               & "end record"
               & LF
               & "f: () -> none = value: record = (first: true, of false) "
               & "end f"
               & LF,
            when Catalogue.Pointer_Union_Use =>
               "none_found: atom"
               & LF
               & "maybe_ptr: type = none_found | ptr mut u32"
               & LF
               & LF
               & "bad: () -> (value: u32) ="
               & LF
               & "    mut cell: u32 = 1"
               & LF
               & "    m: maybe_ptr = addr cell"
               & LF
               & "    value = m.val"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Packed_Image =>
               "image: type = layout(packed) struct"
               & LF
               & "    value: u2 at 0..1"
               & LF
               & "end image"
               & LF
               & "f: () -> none ="
               & LF
               & "    mut x: image = zeroed"
               & LF
               & "    _ = addr x.value"
               & LF
               & "end f"
               & LF,
            when Catalogue.Place_Required =>
               "replace: (inout left: u32, inout right: u32) -> none ="
               & LF
               & "    left = 1"
               & LF
               & "    right = 2"
               & LF
               & "end replace"
               & LF
               & LF
               & "public main: () -> (code: i32) ="
               & LF
               & "    mut value: u32 = 0"
               & LF
               & "    replace(value, value)"
               & LF
               & "    code = 0"
               & LF
               & "end main"
               & LF,
            when Catalogue.Type_Declaration_Form =>
               "bytes: type (t: type, fixed n: u32) = [n]t"
               & LF
               & "bad: type = bytes(u8)"
               & LF,
            when Catalogue.Signature_Form =>
               "duplicated: type = (value: i32, value: bool) -> none"
               & LF,
            when Catalogue.Generic_Deduction =>
               "phantom: (t: type, value: i32) -> (result: i32) = value "
               & "end phantom"
               & LF
               & LF
               & "public main: () -> (code: i32) = phantom(7) end main"
               & LF,
            when Catalogue.Conformance_Form =>
               "left: type = concept (t: type) is right"
               & LF
               & "end left"
               & LF
               & LF
               & "right: type = concept (t: type) is left"
               & LF
               & "end right"
               & LF,
            when Catalogue.Erased_Contract =>
               "",
            when Catalogue.Noreturn_Contract =>
               "stop: () -> noreturn ="
               & LF
               & "end stop"
               & LF,
            when Catalogue.Memory_Contract =>
               "",
            when Catalogue.Machine_Entry_Contract =>
               "extern(interrupt) tick: (count: u32) -> none = end tick"
               & LF,
            when Catalogue.Foreign_Boundary =>
               "extern(c) collect: (count: i32, ...) -> none"
               & LF
               & "bad: () -> none ="
               & LF
               & "    collect(count: 1)"
               & LF
               & "end bad"
               & LF,
            when Catalogue.Linkage_Contract =>
               "extern(c) link(symbol: ""foreign_entry+8"") bad: () -> non"
               & "e"
               & LF,
            when Catalogue.Traversal_Source =>
               "public main: () -> (code: i32) ="
               & LF
               & "    code = 1"
               & LF
               & "    for item in false..true do"
               & LF
               & "        _ = 0"
               & LF
               & "    end for"
               & LF
               & "end main"
               & LF,
            when Catalogue.No_Toolchain =>
               "",
            when Catalogue.Toolchain_Failed =>
               "",
            when Catalogue.Entry_Point_Missing =>
               "",
            when Catalogue.Argument_Not_In_A_Register =>
               "",
            when Catalogue.Frame_Not_Addressable =>
               "",
            when Catalogue.Image_Materialization_Limit =>
               "",
            when Catalogue.Panic_Contract_Invalid =>
               "",
            when Catalogue.Firmware_Frame_Exceeds_Stack =>
               "");

end Landin.Diagnostics.Explanations;
