#!/usr/bin/env python3
"""Generate compiler provenance without checkout paths or wall-clock time."""
import argparse
import hashlib
import re
from pathlib import Path
import subprocess


BUILD_SCRIPTS = (
    'scripts/build.sh', 'scripts/env.sh', 'scripts/build_lock.py',
    'scripts/build_config.py', 'scripts/build_identity.py',
    'scripts/toolchain.sh', 'environments/pins.sh',
)


def inputs(root):
    """Compiler sources, test sources and native build policy; never prose."""
    paths = set(BUILD_SCRIPTS)
    ada = root / 'compiler/ada'
    paths.update(p.relative_to(root).as_posix() for p in ada.glob('*.gpr'))
    for directory in ('src', 'tests/src'):
        paths.update(p.relative_to(root).as_posix()
                     for p in (ada / directory).rglob('*')
                     if p.is_file() and p.suffix in ('.ads', '.adb', '.c', '.h'))
    return sorted(path for path in paths if (root / path).is_file())


def git(root, *args):
    try:
        result = subprocess.run(['git', '-C', str(root), *args],
                                capture_output=True, check=False)
    except FileNotFoundError:
        return None
    return result.stdout if result.returncode == 0 else None


def identity(root, mode):
    paths = inputs(root)
    digest = hashlib.sha256()
    for name in paths:
        content = (root / name).read_bytes()
        digest.update(name.encode() + b'\0')
        digest.update(str(len(content)).encode() + b'\0' + content)
    head = git(root, 'rev-parse', '--show-toplevel')
    # Do not borrow the containing repository's identity for an archive.
    repository = head is not None and Path(head.decode().strip()).resolve() == root.resolve()
    revision = git(root, 'rev-parse', '--verify', 'HEAD') if repository else None
    dirty = False
    version = ''
    if revision is not None:
        tracked = git(root, 'ls-files', '-z')
        if tracked is None:
            raise RuntimeError('cannot inspect compiler input inventory')
        tracked_paths = {name.decode() for name in tracked.split(b'\0') if name}
        # Every tracked edit marks the checkout dirty; the digest remains
        # restricted to compiler inputs. Untracked/ignored build outputs do not.
        status = git(root, 'status', '--porcelain=v1', '-z',
                     '--untracked-files=no')
        if status is None:
            raise RuntimeError('cannot inspect checkout status')
        tags = git(root, 'tag', '--points-at', 'HEAD')
        if tags is None:
            raise RuntimeError('cannot inspect exact release tags')
        versions = [tag[1:] for tag in tags.decode().splitlines()
                    if re.fullmatch(r'v[0-9]+(?:\.[0-9]+)+', tag)]
        if len(versions) > 1:
            raise RuntimeError('multiple release tags identify HEAD: '
                               + ', '.join(versions))
        version = versions[0] if versions else ''
        dirty = bool(status) or not set(paths).issubset(tracked_paths)
    return (revision.decode().strip() if revision else 'unknown',
            digest.hexdigest(), dirty, mode, version)


def render(root, mode):
    revision, digest, dirty, mode, version = identity(root, mode)
    return ('--  Generated by scripts/build_identity.py; do not edit.\n'
            'with Landin.Targets.Selection;\n\n'
            'package Landin.Build_Identity is\n'
            f'   Release_Version : constant String := "{version}";\n'
            f'   Revision : constant String := "{revision}";\n'
            '   Source_Digest : constant String :=\n'
            f'     "{digest}";\n'
            f'   Dirty : constant Boolean := {str(dirty)};\n'
            f'   Mode : constant String := "{mode}";\n'
            '   Host_Triplet : constant String :=\n'
            '     Landin.Targets.Selection.Build_Triplet;\n'
            'end Landin.Build_Identity;\n')


def generate(root, mode, output):
    text = render(root, mode)
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text() != text:
        temporary = output.with_suffix('.tmp')
        temporary.write_text(text)
        temporary.replace(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    parser.add_argument('--mode', choices=('debug', 'release'), required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--manifest', action='store_true')
    args = parser.parse_args()
    if args.manifest:
        checksum = hashlib.sha256(render(args.root, args.mode).encode()).hexdigest()
        print(f'{checksum} identity {args.output}')
    else:
        generate(args.root, args.mode, args.output)


if __name__ == '__main__':
    main()
