#!/usr/bin/env python3
"""Generate the regex-based Landin editor grammars from one vocabulary."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from xml.sax.saxutils import escape

from landin_highlight import BUILTIN_MODULES, CONSTANTS, KEYWORDS, TYPES


ROOT = Path(__file__).resolve().parent
GENERATED = "Generated by highlight/generate.py; do not edit by hand."


def words(values: set[str]) -> str:
    return "|".join(sorted(values, key=lambda value: (-len(value), value)))


def textmate() -> str:
    keyword = rf"\b(?:{words(KEYWORDS)})\b"
    builtin_type = rf"\b(?:{words(TYPES)}|[ui](?:0|[1-9][0-9]{{0,2}}))\b"
    constants = rf"\b(?:{words(CONSTANTS)})\b"
    modules = rf"\b(?:{words(BUILTIN_MODULES)})\b"
    grammar = {
        "name": "Landin",
        "scopeName": "source.landin",
        "fileTypes": ["ldn"],
        "patterns": [
            {"include": "#comments"},
            {"include": "#literals"},
            {"match": builtin_type, "name": "storage.type.builtin.landin"},
            {"match": constants, "name": "constant.language.landin"},
            {"match": modules, "name": "support.module.landin"},
            {"match": keyword, "name": "keyword.control.landin"},
            {
                "match": r"\b([a-z_][a-z0-9_]*)(?=\s*:\s*(?:type|atom)\b)",
                "name": "entity.name.type.landin",
            },
            {
                "match": r"\b([a-z_][a-z0-9_]*)(?=\s*:\s*\([^\n]*\)\s*->)",
                "name": "entity.name.function.landin",
            },
            {
                "match": r"\b[a-z_][a-z0-9_]*(?=\s*\()",
                "name": "entity.name.function.call.landin",
            },
            {
                "match": r"(?<=\.)[a-z_][a-z0-9_]*\b",
                "name": "variable.other.member.landin",
            },
            {
                "match": r"(?:\+%|-%|\*%|:=|->|\.\.<|\.\.|<<|>>|==|<>|<=|>=|[-+*/%<>=!&|^~])",
                "name": "keyword.operator.landin",
            },
        ],
        "repository": {
            "comments": {
                "patterns": [
                    {"match": r"---.*$", "name": "comment.line.documentation.landin"},
                    {"include": "#block-comment"},
                    {"match": r"--.*$", "name": "comment.line.double-dash.landin"},
                ]
            },
            "block-comment": {
                "begin": r"--\(",
                "beginCaptures": {"0": {"name": "punctuation.definition.comment.begin.landin"}},
                "end": r"\)--",
                "endCaptures": {"0": {"name": "punctuation.definition.comment.end.landin"}},
                "name": "comment.block.landin",
                "patterns": [{"include": "#block-comment"}],
            },
            "literals": {
                "patterns": [
                    {
                        "begin": r'("{3,})',
                        "end": r"\1",
                        "name": "string.quoted.other.raw.landin",
                    },
                    {
                        "begin": '"',
                        "end": '"|$',
                        "name": "string.quoted.double.landin",
                        "patterns": [{"match": r"\\.", "name": "constant.character.escape.landin"}],
                    },
                    {
                        "begin": "'",
                        "end": "'|$",
                        "name": "string.quoted.single.landin",
                        "patterns": [{"match": r"\\.", "name": "constant.character.escape.landin"}],
                    },
                    {
                        "match": r"\b(?:0[xX][0-9A-Fa-f_]+(?:\.[0-9A-Fa-f_]+)?(?:[pP][-+]?[0-9]+)?|0[bB][01_]+|0[oO][0-7_]+|[0-9][0-9_]*(?:\.(?!\.)[0-9_]+)?(?:[eE][-+]?[0-9]+)?)\b",
                        "name": "constant.numeric.landin",
                    },
                ]
            },
        },
        "metadata": {"comment": GENERATED},
    }
    return json.dumps(grammar, indent=2, ensure_ascii=False) + "\n"


def vim() -> str:
    def declarations(group: str, values: set[str]) -> str:
        return f"syntax keyword {group} {' '.join(sorted(values))}"

    return "\n".join(
        [
            f'" {GENERATED}',
            "if exists('b:current_syntax') | finish | endif",
            "syntax case match",
            "syntax keyword landinTodo TODO FIXME XXX contained",
            r'syntax region landinString start=/"/ skip=/\\./ end=/"/ oneline',
            r"syntax region landinCharacter start=/'/ skip=/\\./ end=/'/ oneline",
            r'syntax region landinRawString start=/\z("\{3,}\)/ end=/\z1/ keepend',
            r"syntax match landinNumber /\<\%(0[xX][0-9A-Fa-f_]\+\%([.][0-9A-Fa-f_]\+\)\?\%([pP][-+]\?[0-9]\+\)\?\|0[bB][01_]\+\|0[oO][0-7_]\+\|[0-9][0-9_]*\%([.][0-9_]\+\)\?\%([eE][-+]\?[0-9]\+\)\?\)\>/",
            declarations("landinKeyword", KEYWORDS),
            declarations("landinType", TYPES),
            declarations("landinConstant", CONSTANTS),
            declarations("landinBuiltinModule", BUILTIN_MODULES),
            r"syntax match landinWidthType /\<[ui]\%(0\|[1-9][0-9]\{0,2}\)\>/",
            r"syntax match landinFunction /\<[a-z_][a-z0-9_]*\ze\s*(/",
            r"syntax match landinMember /\.\zs[a-z_][a-z0-9_]*/",
            r"syntax match landinOperator /\%(+%\|-%\|\*%\|:=\|->\|\.\.<\|\.\.\|<<\|>>\|==\|<>\|<=\|>=\|[-+*\/%<>=!&|^~]\)/",
            "syntax match landinLineComment /--.*$/ contains=landinTodo",
            "syntax match landinDocComment /---.*$/ contains=landinTodo",
            r"syntax region landinBlockComment start=/--(/ end=/)--/ contains=landinBlockComment,landinTodo keepend extend",
            "highlight default link landinKeyword Keyword",
            "highlight default link landinType Type",
            "highlight default link landinWidthType Type",
            "highlight default link landinConstant Constant",
            "highlight default link landinBuiltinModule Include",
            "highlight default link landinFunction Function",
            "highlight default link landinMember Identifier",
            "highlight default link landinOperator Operator",
            "highlight default link landinNumber Number",
            "highlight default link landinString String",
            "highlight default link landinRawString String",
            "highlight default link landinCharacter Character",
            "highlight default link landinLineComment Comment",
            "highlight default link landinDocComment SpecialComment",
            "highlight default link landinBlockComment Comment",
            "highlight default link landinTodo Todo",
            "let b:current_syntax = 'landin'",
            "",
        ]
    )


def nano() -> str:
    color = lambda name, values: f'color {name} "\\<({"|".join(sorted(values))})\\>"'
    return "\n".join(
        [
            f"# {GENERATED}",
            'syntax "landin" "\\.ldn$"',
            color("brightblue", KEYWORDS),
            color("brightgreen", TYPES),
            color("magenta", CONSTANTS),
            color("cyan", BUILTIN_MODULES),
            'color brightgreen "\\<[ui](0|[1-9][0-9]{0,2})\\>"',
            'color brightcyan "\\<[a-z_][a-z0-9_]*[[:space:]]*\\("',
            'color yellow "\\<((0[xX][0-9A-Fa-f_]+)|(0[bB][01_]+)|(0[oO][0-7_]+)|([0-9][0-9_]*))\\>"',
            'color brightmagenta start="\\\"" end="\\\""',
            'color brightblack "---.*$"',
            'color brightblack "--.*$"',
            'color brightblack start="--\\(" end="\\)--"',
            "",
        ]
    )


def kate() -> str:
    items = lambda values: "".join(f"<item>{escape(value)}</item>" for value in sorted(values))
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- {GENERATED} -->
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Landin" section="Sources" extensions="*.ldn" mimetype="text/x-landin" version="1" kateversion="5.0" author="Landin contributors" license="MIT OR Apache-2.0">
  <highlighting>
    <list name="keywords">{items(KEYWORDS)}</list>
    <list name="types">{items(TYPES)}</list>
    <list name="constants">{items(CONSTANTS)}</list>
    <list name="modules">{items(BUILTIN_MODULES)}</list>
    <contexts>
      <context name="Normal" attribute="Normal Text" lineEndContext="#stay">
        <StringDetect String="--(" attribute="Comment" context="Block Comment"/>
        <Detect2Chars char="-" char1="-" attribute="Comment" context="Line Comment"/>
        <keyword String="keywords" attribute="Keyword"/>
        <keyword String="types" attribute="Data Type"/>
        <keyword String="constants" attribute="Constant"/>
        <keyword String="modules" attribute="Import"/>
        <RegExpr String="\\b[ui](0|[1-9][0-9]{{0,2}})\\b" attribute="Data Type"/>
        <RegExpr String="\\b(0[xX][0-9A-Fa-f_]+|0[bB][01_]+|0[oO][0-7_]+|[0-9][0-9_]*)\\b" attribute="Number"/>
        <DetectChar char="&quot;" attribute="String" context="String"/>
        <DetectChar char="'" attribute="Char" context="Char"/>
      </context>
      <context name="Line Comment" attribute="Comment" lineEndContext="#pop"/>
      <context name="Block Comment" attribute="Comment" lineEndContext="#stay">
        <StringDetect String="--(" context="Block Comment"/>
        <StringDetect String=")--" context="#pop"/>
      </context>
      <context name="String" attribute="String" lineEndContext="#pop">
        <HlCStringChar attribute="Special Character"/>
        <DetectChar char="&quot;" context="#pop"/>
      </context>
      <context name="Char" attribute="Char" lineEndContext="#pop">
        <HlCChar attribute="Special Character"/>
        <DetectChar char="'" context="#pop"/>
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword" defStyleNum="dsKeyword"/>
      <itemData name="Data Type" defStyleNum="dsDataType"/>
      <itemData name="Constant" defStyleNum="dsConstant"/>
      <itemData name="Import" defStyleNum="dsImport"/>
      <itemData name="Number" defStyleNum="dsDecVal"/>
      <itemData name="String" defStyleNum="dsString"/>
      <itemData name="Char" defStyleNum="dsChar"/>
      <itemData name="Special Character" defStyleNum="dsSpecialChar"/>
      <itemData name="Comment" defStyleNum="dsComment"/>
    </itemDatas>
  </highlighting>
  <general><comments><comment name="singleLine" start="--"/><comment name="multiLine" start="--(" end=")--" region="Block Comment"/></comments><keywords casesensitive="1"/></general>
</language>
'''


def notepad_plus_plus() -> str:
    keyword = " ".join(sorted(KEYWORDS))
    types = " ".join(sorted(TYPES))
    constants = " ".join(sorted(CONSTANTS | BUILTIN_MODULES))
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- {GENERATED} -->
<NotepadPlus>
  <UserLang name="Landin" ext="ldn" udlVersion="2.1">
    <Settings>
      <Global caseIgnored="no" allowFoldOfComments="yes" foldCompact="no" forcePureLC="0" decimalSeparator="0"/>
      <Prefix Keywords1="no" Keywords2="no" Keywords3="no" Keywords4="no" Keywords5="no" Keywords6="no" Keywords7="no" Keywords8="no"/>
    </Settings>
    <KeywordLists>
      <Keywords name="Comments">00-- 01 02 03--( 04)--</Keywords>
      <Keywords name="Numbers, prefix1">0x 0X 0b 0B 0o 0O</Keywords>
      <Keywords name="Numbers, prefix2"></Keywords>
      <Keywords name="Numbers, extras1">_</Keywords>
      <Keywords name="Numbers, extras2"></Keywords>
      <Keywords name="Numbers, suffix1"></Keywords>
      <Keywords name="Numbers, suffix2"></Keywords>
      <Keywords name="Numbers, range"></Keywords>
      <Keywords name="Operators1">+ - * / % &amp; | ^ ~ = &lt; &gt; ! : . ,</Keywords>
      <Keywords name="Operators2"></Keywords>
      <Keywords name="Folders in code1, open">if struct concept variant begin match</Keywords>
      <Keywords name="Folders in code1, middle">else elsif</Keywords>
      <Keywords name="Folders in code1, close">end</Keywords>
      <Keywords name="Folders in code2, open"></Keywords>
      <Keywords name="Folders in code2, middle"></Keywords>
      <Keywords name="Folders in code2, close"></Keywords>
      <Keywords name="Folders in comment, open">--(</Keywords>
      <Keywords name="Folders in comment, middle"></Keywords>
      <Keywords name="Folders in comment, close">)--</Keywords>
      <Keywords name="Keywords1">{escape(keyword)}</Keywords>
      <Keywords name="Keywords2">{escape(types)}</Keywords>
      <Keywords name="Keywords3">{escape(constants)}</Keywords>
      <Keywords name="Keywords4"></Keywords>
      <Keywords name="Keywords5"></Keywords>
      <Keywords name="Keywords6"></Keywords>
      <Keywords name="Keywords7"></Keywords>
      <Keywords name="Keywords8"></Keywords>
      <Keywords name="Delimiters">00&quot; 01\\ 02&quot; 03&apos; 04\\ 05&apos; 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23</Keywords>
    </KeywordLists>
    <Styles>
      <WordsStyle name="DEFAULT" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0"/>
      <WordsStyle name="COMMENTS" fgColor="608060" bgColor="FFFFFF" fontName="" fontStyle="2" nesting="0"/>
      <WordsStyle name="LINE COMMENTS" fgColor="608060" bgColor="FFFFFF" fontName="" fontStyle="2" nesting="0"/>
      <WordsStyle name="NUMBERS" fgColor="9A6500" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0"/>
      <WordsStyle name="KEYWORDS1" fgColor="0000A0" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0"/>
      <WordsStyle name="KEYWORDS2" fgColor="006060" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0"/>
      <WordsStyle name="KEYWORDS3" fgColor="7A007A" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0"/>
      <WordsStyle name="OPERATORS" fgColor="404040" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0"/>
      <WordsStyle name="FOLDER IN CODE1" fgColor="0000A0" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0"/>
      <WordsStyle name="FOLDER IN CODE2" fgColor="0000A0" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0"/>
      <WordsStyle name="FOLDER IN COMMENT" fgColor="608060" bgColor="FFFFFF" fontName="" fontStyle="2" nesting="0"/>
      <WordsStyle name="DELIMITERS1" fgColor="A02020" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0"/>
    </Styles>
  </UserLang>
</NotepadPlus>
'''


def outputs() -> dict[Path, str]:
    tm = textmate()
    result = {
        ROOT / "textmate/syntaxes/landin.tmLanguage.json": tm,
        ROOT / "sublime/Landin.tmLanguage": tm,
        ROOT / "vim/syntax/landin.vim": vim(),
        ROOT / "nano/landin.nanorc": nano(),
        ROOT / "kate/landin.xml": kate(),
        ROOT / "notepad-plus-plus/Landin.xml": notepad_plus_plus(),
    }
    query_copies = {
        "nvim/queries/landin/highlights.scm": "highlights.scm",
        "nvim/queries/landin/indents.scm": "indents.scm",
        "nvim/queries/landin/folds.scm": "folds.scm",
        "nvim/queries/landin/locals.scm": "locals.scm",
        "nvim/queries/landin/textobjects.scm": "textobjects.scm",
        "nvim/queries/landin/tags.scm": "tags.scm",
        "helix/runtime/queries/landin/highlights.scm": "highlights.scm",
        "helix/runtime/queries/landin/indents.scm": "indents.scm",
        "helix/runtime/queries/landin/folds.scm": "folds.scm",
        "helix/runtime/queries/landin/textobjects.scm": "textobjects.scm",
        "helix/runtime/queries/landin/locals.scm": "locals.scm",
        "helix/runtime/queries/landin/tags.scm": "tags.scm",
        "zed/languages/landin/highlights.scm": "highlights.scm",
        "zed/languages/landin/indents.scm": "indents.scm",
        "zed/languages/landin/brackets.scm": "brackets.scm",
    }
    for destination, source in query_copies.items():
        result[ROOT / destination] = (ROOT / "tree-sitter/queries" / source).read_text(
            encoding="utf-8"
        )
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT.parent))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"stale generated highlighter: {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
